### PR TITLE
Ensure synced deploys of a block are held in the correct order

### LINKED ISSUE #3253: Node failed to join to nctl network while new deploys were being sent
see failure in https://drone-auto-casper-network.casperlabs.io/casper-network/casper-node/6072/1/4

### PR DESCRIPTION
**Pull request by Fraser999**
This PR ensures that during chain sync, deploys which are fetched in parallel are inserted into the block for execution in the correct order.

It also updates the `Debug` impl for the mirrored `DeployHash` type in casper-types to use hex-encoded notation as per other hash digests.

Finally, it downgrades an `error!` log in the RPC server to `warn!` as it could be triggered by an invalid client request and doesn't represent an actual internal node error.

Closes #3253.

### CODE REVIEW

File: node/src/components/chain_synchronizer/operations.rs [hunk 1]
```diff
@@ -2240,21 +2247,37 @@ async fn fetch_and_store_deploys<REv>(
...
+        + From<NetworkInfoRequest>
+        + From<ControlAnnouncement>,
 {
     let start_instant = Timestamp::now();
 
-    let hashes: Vec<_> = hashes.cloned().collect();
-    let mut deploys: Vec<Deploy> = Vec::with_capacity(hashes.len());
-    let mut stream = futures::stream::iter(hashes)
-        .map(|hash| fetch_and_store_deploy(hash, ctx))
+    let mut ordered_deploys = BTreeMap::new();
```
Comment (goral09) [inline node/src/components/chain_synchronizer/operations.rs]: We could use the `mut deploys` from before and insert at an index as well, right? Not sure if a `BTreeMap` isn't a small overkill for this.

**Review by goral09 — APPROVED** [review]

File: node/src/components/chain_synchronizer/operations.rs (hunk 1 above)
Comment (Fraser999) [reply node/src/components/chain_synchronizer/operations.rs]: Not sure it makes _too_ much of a difference.  Using `Vec::insert` would require actually constructing a Vec with the right number of entries, which would then all get overwritten (and `insert` can panic, making it one more thing to consider during safety reviews of the code).

If we see performance problems, we could indeed switch to a `Vec` and maybe leverage some unsafe methods, but I'd benchmark before doing something like that.

Comment (marc-casperlabs) [reply node/src/components/chain_synchronizer/operations.rs]: Is there anything wrong with `Vec::sort` (but see below for a different approach).

File: node/src/components/chain_synchronizer/operations.rs [hunk 2]
```diff
@@ -2240,21 +2247,37 @@ async fn fetch_and_store_deploys<REv>(
...
+
+    let mut stream = futures::stream::iter(hashes.cloned().enumerate())
+        .map(|(index, hash)| async move { (index, fetch_and_store_deploy(hash, ctx).await) })
         .buffer_unordered(ctx.config.max_parallel_deploy_fetches());
-    while let Some(result) = stream.next().await {
+    while let Some((index, result)) = stream.next().await {
         let deploy = result?;
         trace!("fetched {:?}", deploy);
-        deploys.push(*deploy);
+        if let Some(deploy) = ordered_deploys.insert(index, *deploy) {
```
Comment (marc-casperlabs) [inline node/src/components/chain_synchronizer/operations.rs]: I am not a fan of this. It's a lot of code that is essentially checking that `enumerate` works correctly, right?

Comment (marc-casperlabs) [reply node/src/components/chain_synchronizer/operations.rs]: Can we not replace all of this code, starting from `stream`, with something like this? (I'm assuming `hashes` contains what we need in order):

```rust
let jobs: FuturesOrdered<_> = hashes.into_iter().map(|hash| fetch_and_store_deploy(hash, ctx));
let ordered_deploys: Vec<_> = jobs.collect().await;
```

**Review by marc-casperlabs — COMMENTED** [review]
I _think_ we can simplify this?

File: node/src/components/chain_synchronizer/operations.rs (hunk 2 above)
Comment (goral09) [reply node/src/components/chain_synchronizer/operations.rs]: Ordering thousands of deploys? I would be worried about performance of `PartialEq, Eq` for `Deploy`.

Comment (marc-casperlabs) [reply node/src/components/chain_synchronizer/operations.rs]: Hmm, I would not be concerned about that at all:

1. Ordering a few thousand items should be quick, especially if our ordering is by hash.
2. We actually don't even order anything there :) The `Ordered` part is just keeping the already existing order.

Comment (marc-casperlabs) [reply node/src/components/chain_synchronizer/operations.rs]: There may be merit to using `buffered` instead of `buffer_unordered` instead as well.

Comment (marc-casperlabs) [reply node/src/components/chain_synchronizer/operations.rs]:
```rust
let mut stream = futures::stream::iter(hashes.cloned())
  .map(|hash| async move { fetch_and_store_deploy(hash, ctx).await })
  .buffered(ctx.config.max_parallel_deploy_fetches());
        
let deploys = stream.collect().await;
ctx.metrics
    .observe_fetch_deploys_duration_seconds(start_instant);
Ok(deploys)
```

**Comment by marc-casperlabs** [comment]
After discussion we figured, any approach using `FuturesOrdered` will not work, as it will allow one long fetch to block the remainder from making progress (e.g. if 100 are fetched concurrently with a limit of 5, and the first one is taking 9 minutes to complete, both the manual `FuturesOrdered` and `.buffered`, which actually uses `FuturesOrdered` behind the scenes, will not attempt to fetch a 6th item before the first one has completed).

**Comment by marc-casperlabs** [comment]
With that in mind, I think the sorting-the-Vec approach is simplest in terms of code. As for computational complexity, it has an $O(n \log n)$ sort as the upper bound on complexity.

Note that the `BTreeMap`-based approach has $n$ insertions of $O(\log n)$ complexity, which is the same thing. So it is _not_ worse than the map.

And to complete the code golfing round: Let's replace the entire `while` loop with `let results: BTreeMap<usize, _> = stream.collect().await;`, which :crossed_fingers: is possible?

**Review by marc-casperlabs — APPROVED** [review]
Well, pretty much everything discussed here seems to lead to a valid outcome, so whatever variant you pick LGTM :)

**Review by goral09 — APPROVED** [review]

**Comment by Fraser999** [comment]
bors merge
