### PR TITLE
Fix sync-to-genesis

### LINKED ISSUE #3186: Sync-to-genesis should sync as far as the highest block at the end of fast-syncin
sync-to-genesis can finish before "filling in" all the missing blocks and the related data, depending upon the trusted hash used if any.  We should sync forwards as far as the highest block at the end of the fast-sync process, as that block and all subsequent will be guaranteed to be complete, since that was the point at which consensus began execution.

### PR DESCRIPTION
**Pull request by Fraser999**
This PR changes sync-to-genesis to ensure it syncs forward far enough so that once it's complete the node has a full sequence of complete blocks and corresponding global state.

The main thrust of the change is that sync-from-genesis now uses the block returned by the fast-sync process as its trusted block.  Sync-to-genesis synchronises as far as that block, and all subsequent ones are guaranteed to be "complete" as they will have been executed while the node is in participating mode.

It also provides a fix for an issue discovered while testing the PR: namely that the `completed_blocks` in storage was not being adjusted after a hard reset to account for the fact that some blocks could have been removed.

Finally, it fixes an issue whereby `execute_blocks` was being passed the key block info for the trusted block rather than the most recent block.

Closes #3186, #3192 and #3193.

### CODE REVIEW

File: node/src/components/storage/disjoint_sequences.rs [hunk 1]
```diff
@@ -437,6 +457,94 @@ mod tests {
...
+    #[test]
+    fn should_truncate() {
+        const SEQ_HIGH: Sequence = Sequence { high: 11, low: 9 };
+        const SEQ_MID: Sequence = Sequence { high: 6, low: 6 };
+        const SEQ_LOW: Sequence = Sequence { high: 3, low: 1 };
+        fn new_sequences() -> DisjointSequences {
+            DisjointSequences {
+                sequences: vec![SEQ_HIGH, SEQ_MID, SEQ_LOW],
+            }
+        }
```
Comment (goral09) [inline node/src/components/storage/disjoint_sequences.rs]: Can't you initialize it once and then only clone it?

Comment (Fraser999) [reply node/src/components/storage/disjoint_sequences.rs]: `DisjointSequences` isn't clonable.  I can add that behind a `test` feature-gate if you have a strong preference, but I'm not sure it's worth it?

Comment (goral09) [reply node/src/components/storage/disjoint_sequences.rs]: It's not a blocker but it _could_ be clonable since it's just a couple tuples.

**Review by goral09 — APPROVED** [review]

File: node/src/components/storage/disjoint_sequences.rs (hunk 1 above)
Comment (Fraser999) [reply node/src/components/storage/disjoint_sequences.rs]: Fair enough - done in [c13fba6](https://github.com/casper-network/casper-node/pull/3191/commits/c13fba604943a73ec0642a72f712e3a433d75525).

File: node/src/components/storage/disjoint_sequences.rs [hunk 2]
```diff
@@ -96,6 +96,7 @@ impl Sequence {
 /// For example, if `sequences` contains `[9,9], [7,3]` and `8` is inserted, then `sequences` will
 /// be reduced to `[9,3]`.
 #[derive(Default, Debug, DataSize)]
+#[cfg_attr(test, derive(Clone))]
```
Comment (goral09) [inline node/src/components/storage/disjoint_sequences.rs:99]: It could have been just `Clone` without the test attribute.

**Review by fizyk20 — APPROVED** [review]

**Comment by Fraser999** [comment]
bors merge
