### PR TITLE
GH-3097: Disabled contracts

### LINKED ISSUE #3097: Calling contract with StoredContractByHash after using storage::disable_contract_version should raise error
Contract API storage::disable_contract_version takes contract_package_hash, and contract_hash, and even after successfully disabling a contract by it’s hash it’s still callable by StoredContractByHash/StoredContractByName variant. Calling same disabled contract through StoredVersionedContractByHash does properly fail as expected. 

We need a regression test to prove this bug, and a fix.

### PR DESCRIPTION
**Pull request by mpapierski**
Closes #3097

This PR makes the contract execution flow easier to follow by moving most of the logic shared between call_contract and call_versioned_contract into execute_contract. It decreases duplication and allows for an extra validation step that will reject calls to disabled contract hashes - when a disabled contract is now called, a special error `DisabledContract(contract_hash)` will be raised.

### CODE REVIEW

File: execution_engine/src/core/execution/error.rs [hunk 1]
```diff
@@ -170,6 +170,9 @@ pub enum Error {
     /// The runtime stack is `None`.
     #[error("Runtime stack missing")]
     MissingRuntimeStack,
+    /// Contract is disabled.
+    #[error("Contract is disabled")]
+    DisabledContract(ContractHash),
```
Comment (georgepisaltu) [inline execution_engine/src/core/execution/error.rs:175]: Does it help users debug fails if we show the contract hash in the error message?

**Review by georgepisaltu — COMMENTED** [review]
Looks good, just one question.

File: execution_engine/src/core/runtime/mod.rs [hunk 2]
```diff
@@ -1196,12 +1137,92 @@ where
...
+                }
+
+                (contract, contract_hash, contract_package)
+            }
+            CallContractIdentifier::ContractPackage {
+                contract_package_hash,
+                version,
+            } => {
+                let contract_package_key = contract_package_hash.into();
+                let contract_package = match self.context.read_gs(&contract_package_key)? {
```
Comment (darthsiroftardis) [inline execution_engine/src/core/runtime/mod.rs]: I have a thought here, if I understand correctly, the `lock_status` here would tell us if a contract package is locked, we could then exit early if the `ContractVersion` is higher than 1?

**Review by darthsiroftardis — COMMENTED** [review]
Overall code looks fine, I have one outstanding question about a possible early exit, will approve once that has been resolved

File: execution_engine/src/core/runtime/mod.rs [hunk 3]
```diff
@@ -1196,12 +1137,92 @@ where
...
+                    Some(StoredValue::Contract(contract)) => contract,
+                    Some(_) => {
+                        return Err(Error::InvalidContract(contract_hash));
+                    }
+                    None => return Err(Error::KeyNotFound(key)),
+                };
+
+                let contract_package_hash = contract.contract_package_hash();
+                let contract_package_key = contract_package_hash.into();
+                let contract_package = match self.context.read_gs(&contract_package_key)? {
```
Comment (rafal-ch) [inline execution_engine/src/core/runtime/mod.rs]: `execute_contracts` has stronger validation requirements than the `call_contract` had before. For example, in `call_contract` we didn't validate the `contract_package_key`.

Maybe it's perfectly ok, but I just wanted to bring this to your attention.

File: execution_engine/src/core/runtime/mod.rs [hunk 4]
```diff
@@ -1196,12 +1137,92 @@ where
...
-        contract_package: ContractPackage,
-        contract_hash: ContractHash,
-        contract: Contract,
-        entry_point: EntryPoint,
+        identifier: CallContractIdentifier,
+        entry_point_name: &str,
         args: RuntimeArgs,
     ) -> Result<CLValue, Error> {
+        let (contract, contract_hash, contract_package) = match identifier {
+            CallContractIdentifier::Contract { contract_hash } => {
```
Comment (rafal-ch) [inline execution_engine/src/core/runtime/mod.rs:1145]: These two match arms (`::Contract` and `::ContractPackage`) still has the following code in common. Maybe consider moving it in front of the match call.

```
                let key = contract_hash.into();
                let contract = match self.context.read_gs(&key)? {
                    Some(StoredValue::Contract(contract)) => contract,
                    Some(_) => {
                        return Err(Error::InvalidContract(contract_hash));
                    }
                    None => return Err(Error::KeyNotFound(key)),
                };

                let contract_package_key = contract_package_hash.into();
                let contract_package = match self.context.read_gs(&contract_package_key)? {
                    Some(StoredValue::ContractPackage(contract_package)) => contract_package,
                    Some(_) => {
                        return Err(Error::InvalidContractPackage(contract_package_hash));
                    }
                    None => return Err(Error::KeyNotFound(contract_package_key)),
                };
```

File: execution_engine_testing/tests/src/test/regression/gh_3097.rs [hunk 5]
```diff
@@ -0,0 +1,354 @@
...
+        .exec(call_by_hash_v1_request)
+        .expect_failure()
+        .commit();
+
+    let error = builder.get_error().expect("should have error");
+    assert!(
+        matches!(
+            error,
+            casper_execution_engine::core::engine_state::Error::Exec(
+                casper_execution_engine::core::execution::Error::DisabledContract(disabled_contract_hash)
```
Comment (rafal-ch) [inline execution_engine_testing/tests/src/test/regression/gh_3097.rs]: The test looks ok, but I had some trouble understanding why we expect this contract to be disabled. This is (probably) because earlier we executed the other contract that called `storage::disable_contract_version()` on `contract_hash_v1`.

Can you maybe consider adding more comments that explain the test flow for people not that well acquainted with the execution engine?

File: execution_engine/src/core/runtime/mod.rs (hunk 2 above)
Comment (mpapierski) [reply execution_engine/src/core/runtime/mod.rs]: I don't think it's necessary. If calling a locked contract with a version larger than 1, we'll never get to `execute_contract` as the validation happens very early here https://github.com/casper-network/casper-node/blob/1d3b388d5b62b8889c6bd01f0798b3cb20455bf1/execution_engine/src/core/engine_state/executable_deploy_item.rs#L863-L867

File: execution_engine/src/core/runtime/mod.rs (hunk 3 above)
Comment (mpapierski) [reply execution_engine/src/core/runtime/mod.rs]: I moved this code from `call_versioned_contract,` so the validation didn't happen here in `execute_contract,` but once we got here, it was already valid. This PR just moves it on different level.

File: execution_engine/src/core/runtime/mod.rs (hunk 4 above)
Comment (mpapierski) [reply execution_engine/src/core/runtime/mod.rs:1145]: I tried different approaches, but I'm struggling to see an easy way to refactor this to avoid duplication nicely. The only thing that came to my mind was to use `self.context.read_gs_typed` rather than much longer `read_gs.` Hope that helps

File: execution_engine_testing/tests/src/test/regression/gh_3097.rs (hunk 5 above)
Comment (mpapierski) [reply execution_engine_testing/tests/src/test/regression/gh_3097.rs]: Fair point. I renamed `contract_hash_v1`  and _v2 into `enabled_contract_hash` and `disabled_contract_hash` to make this a bit more readable. I hope that helps with readability

File: execution_engine/src/core/execution/error.rs (hunk 1 above)
Comment (mpapierski) [reply execution_engine/src/core/execution/error.rs:175]: I do believe it helps. When you have a smart contract that does series of calls i.e.

```rust
runtime::call_contract(foo_contract_hash, ...);
runtime::call_contract(bar_contract_hash, ...);
runtime::call_contract(baz_contract_hash, ...);
```

It'll be helpful for the developer to see that call to `bar_contract_hash` failed. Then based on that a developer can query `bar_contract_hash` off-chain, confirm it's disabled, and then find a contract hash that's enabled.

File: execution_engine/src/core/runtime/mod.rs (hunk 4 above)
Comment (rafal-ch) [reply execution_engine/src/core/runtime/mod.rs:1145]: Cool, looks much better with `read_gs_typed` :+1:

**Review by rafal-ch — APPROVED** [review]
No blockers from my side.
LGTM :+1:

File: types/src/contracts.rs [hunk 6]
```diff
@@ -808,6 +816,16 @@ impl ContractPackage {
...
     }
 
+    fn find_contract_version_key_by_hash(
+        &self,
+        contract_hash: &ContractHash,
+    ) -> Option<&ContractVersionKey> {
+        self.versions
+            .iter()
+            .filter_map(|(k, v)| if v == contract_hash { Some(k) } else { None })
+            .next()
```
Comment (Fraser999) [inline types/src/contracts.rs:826]:
```suggestion
            .find_map(|(k, v)| if v == contract_hash { Some(k) } else { None })
```

**Review by Fraser999 — APPROVED** [review]

**Review by darthsiroftardis — APPROVED** [review]

File: types/src/contracts.rs (hunk 6 above)
Comment (mpapierski) [reply types/src/contracts.rs:826]: Nice one, applied
