### PR TITLE
Fix the determination of validators for immediate switch blocks

### LINKED ISSUE #3573: Fix historical sync across an emergency upgrade boundary
The test added in #3541 shows that a node attempting to perform historical sync after an upgrade following an emergency upgrade gets stuck trying to sync the immediate switch block of the emergency upgrade. This is likely due to the node erroneously assuming that the validators from the previous switch block should have signed the immediate switch block, where such an assumption is incorrect in regards to an immediate switch block after an emergency upgrade. We have to make sure that a node performing historical sync uses the correct validator set for such blocks.

### PR DESCRIPTION
**Pull request by fizyk20**
This PR makes sure that the validators from immediate switch blocks are determined based on the global states of both the block itself and its parent; in such cases, if the validators have been altered, we need to use the validators from the immediate switch block instead of from the block preceding it.

Fixes the bug confirmed by the test introduced in #3570

Closes #3573

### CODE REVIEW

File: node/src/reactor/main_reactor.rs [hunk 1]
```diff
@@ -960,6 +960,74 @@ impl reactor::Reactor for MainReactor {
...
+                    // the ones we would use normally.
+                    validators_in_block
+                };
+                self.validator_matrix
+                    .register_validator_weights(era_id, validators_to_register.clone());
+                // Crank the reactor so that any synchronizing tasks blocked by the lack of
+                // validators for `era_id` can resume.
+                effect_builder
+                    .immediately()
+                    .event(|_| MainEvent::ReactorCrank)
```
Comment (georgepisaltu) [inline node/src/reactor/main_reactor.rs]: Before cranking, we probably should call `handle_validators` on at least the synchronizer, possibly the accumulator, to make sure they have the most up-to-date information.

**Review by georgepisaltu — COMMENTED** [review]
LGTM

File: node/src/reactor/main_reactor.rs (hunk 1 above)
Comment (fizyk20) [reply node/src/reactor/main_reactor.rs]: The accumulator is for the blocks that are gossiped, isn't it? In such a case it wouldn't be of much use to call `handle_validators` on it, as this will only ever affect blocks in the past, which wouldn't be gossiped anymore.

Calling it on the synchronizer isn't necessary, because the updated validators get read later, anyway, when the synchronizer retries to sync the block and repeats the check if the validators matrix has the relevant era. It could make sense as an optimization, but I'm not sure if it would even make any difference, as cranking the reactor should call `keep_up_instruction` and that will push the sync process further even without us calling `handle_validators`.

Comment (georgepisaltu) [reply node/src/reactor/main_reactor.rs]: In the context we're in now and how we process this event, it makes sense that the synchronizer would be able to do without this (as it is proven to do in the tests which pass on this PR), but I'm making the point we should make behaviors such as updating the validator matrix trigger predictable, which means notifying every interested party about this. I would take it a step further and have a higher-level function for updating the validator matrix which does that plus any necessary event dispatches to ensure that, but it's not necessary.

To the point, I agree it works as is and I'm fine with it merging in this form. Surely not a blocker for me.

File: node/src/reactor/main_reactor/keep_up.rs [hunk 2]
```diff
@@ -393,7 +544,20 @@ impl MainReactor {
...
-        KeepUpInstruction::CheckLater("historical sync leap received".to_string(), Duration::ZERO)
+
+        // We put all the headers we received into storage - if the SyncLeap was valid, we can
+        // trust them, and they will be useful for determining which blocks are immediate switch
+        // blocks.
+        let effects = best_available
+            .headers()
+            .flat_map(move |block_header| {
+                effect_builder
+                    .put_block_header_to_storage(Box::new(block_header.clone()))
```
Comment (rafal-ch) [inline node/src/reactor/main_reactor/keep_up.rs]: Isn't it already stored by the sync leap fetcher [here](https://github.com/casper-network/casper-node/blob/dev/node/src/components/fetcher/fetcher_impls/sync_leap_fetcher.rs#L41-L60)?

File: node/src/reactor/main_reactor.rs [hunk 3]
```diff
@@ -960,6 +960,74 @@ impl reactor::Reactor for MainReactor {
...
+                        return fatal!(
+                            effect_builder,
+                            "couldn't find validators for era {} in block_era_validators",
+                            era_to_check
+                        )
+                        .ignore();
+                    }
+                };
+                // Decide which validators to use for `era_id` in the validators matrix.
+                let validators_to_register = if validators_in_parent == validators_in_block {
```
Comment (rafal-ch) [inline node/src/reactor/main_reactor.rs:1046]: That will compare both public key and weight. I wonder, if only the weight changes, do we consider it a validators update?

File: node/src/reactor/main_reactor/keep_up.rs [hunk 4]
```diff
@@ -464,9 +628,32 @@ impl MainReactor {
...
+                        // immediate switch block - we check for that case by attempting to read
+                        // its parent and seeing whether it is also a switch block; if it is, we
+                        // pass the parent metadata on in the Sync instruction, so that we can read
+                        // the correct set of validators if the validators matrix doesn't have the
+                        // validators for the parent's era yet
+                        let maybe_parent_metadata = self
+                            .storage
+                            .read_block_header(parent_block_header.parent_hash())
+                            .map_err(|err| err.to_string())?
+                            .and_then(|parent_parent_header| {
```
Comment (rafal-ch) [inline node/src/reactor/main_reactor/keep_up.rs]: `grandparent`? ;-)

File: node/src/reactor/main_reactor.rs (hunk 3 above)
Comment (alsrdn) [reply node/src/reactor/main_reactor.rs:1046]: I guess that for the purpose of determining weak vs strict finality correctly we would have to consider the weight as well.

File: node/src/reactor/main_reactor/keep_up.rs (hunk 2 above)
Comment (fizyk20) [reply node/src/reactor/main_reactor/keep_up.rs]: Ha, good point. It was kind of weird to me that they wouldn't be stored, so it makes sense that they actually would :smile:

File: node/src/reactor/main_reactor/keep_up.rs (hunk 4 above)
Comment (fizyk20) [reply node/src/reactor/main_reactor/keep_up.rs]: I guess it might be more readable :wink:

**Review by rafal-ch — APPROVED** [review]
LGTM :+1:

**Review by alsrdn — APPROVED** [review]
LGTM
