### PR TITLE
Remove the integrity check and pid file

### LINKED ISSUE #2707: Remove integrity_check from the node
The "fast-sync" node should not perform any kind of data integrity checks. Apparently, even when the node has some incorrect state it should be able to "repair" it via the process currently known as "archival sync".
Potentially also get rid of the PidFile, but this still need to be agreed.

### PR DESCRIPTION
**Pull request by rafal-ch**
This PR removes:
- the no longer needed process of executing the integrity check
- the "pid file" mechanism used to detect whether the node exited gracefully, as it was only used by the integrity check process

Closes #2707.

### CODE REVIEW

**Comment by rafal-ch** [comment]
Dear reviewers:
I'd like your attention on the three tests that I removed in this PR:
- `missing_trie_keys_should_find_key_of_corrupt_value`
- `lmdb_missing_trie_keys_should_find_key_of_corrupt_value`
- `in_memory_missing_trie_keys_should_find_key_of_corrupt_value`

The removal happened because they test for corrupted value, which was only detected as a part of (now removed) integrity check in `pub fn missing_trie_keys<K, V, T, S, E>()`. But, as usual, when removing tests I'd like to be super-sure that it's a correct move.

File: node/src/cli.rs [hunk 1]
```diff
@@ -153,57 +148,6 @@ impl Cli {
...
-
-                    PidFile::acquire(root.join("initializer.pid"))
-                };
-
-                // Note: Do not change `_pid_file` to `_`, or it will be dropped prematurely.
-                // Instantiating `pid_file` guarantees that it will be dropped _after_ any reactor,
-                // which is what we want.
-                let (_pid_file, pid_outcome_check_integrity) = match pid_file_outcome {
-                    PidFileOutcome::AnotherNodeRunning(_) => {
-                        anyhow::bail!("another node instance is running (pid_file is locked)");
```
Comment (afck) [inline node/src/cli.rs:175]: Maybe we should keep the pid file, and still bail or print the warning, even without the integrity check?

**Review by afck — APPROVED** [review]
Looks good to me, but could use a second approval!

Not sure about removing the pid file mechanism completely.

File: node/src/cli.rs (hunk 1 above)
Comment (rafal-ch) [reply node/src/cli.rs:175]: The removal of pid file was briefly discussed before being put into effect. Surely, I'm open to further changes in this regard.

Let's wait for the feedback from other reviewers.

Comment (afck) [reply node/src/cli.rs:175]: Sure, just a thought. If it was discussed I'm fine with it. :+1:

Comment (fizyk20) [reply node/src/cli.rs:175]: I'd support keeping it in order to detect that another node instance is running, but I don't feel strongly about it.

File: node/src/components/storage.rs [hunk 2]
```diff
@@ -2309,116 +2213,21 @@ fn garbage_collect_block_body_v2_db(
     Ok(())
 }
 
-/// Purges stale entries from the (Merklized) block body database, and checks the integrity of the
-/// remainder if `should_check_integrity` is true.
-#[allow(clippy::too_many_arguments)]
-fn initialize_block_body_v2_db(
```
Comment (fizyk20) [inline node/src/components/storage.rs:2315]: If we want to keep purging stale entries from the database on initialization with a hard reset, there is a lot of code here that will still be needed. It was only done during integrity checks, as it is expensive, but we might still want to do it under some circumstances even without integrity checks. We should probably discuss it.

File: node/src/cli.rs (hunk 1 above)
Comment (Fraser999) [reply node/src/cli.rs:175]: We can bring the pidfile back if we do have a need for it in the future.  For now, I believe we should just remove it.

File: node/src/components/storage.rs (hunk 2 above)
Comment (Fraser999) [reply node/src/components/storage.rs:2315]: As for the pidfile, if we need this code in the future, we can resurrect it.  Seems like it would need reworking somewhat anyway to be viable.

Comment (fizyk20) [reply node/src/components/storage.rs:2315]: Alright, I'm fine with that :+1:

**Review by fizyk20 — APPROVED** [review]
With the decision that removing the PID file and the block removal code is fine, this looks good to me :+1:
