### PR TITLE
Ensure node can transition out of validate mode

### LINKED ISSUE #4012: Investigate nightly test failure
network_soundness.py test failed in [this run](https://drone-auto-casper-network.casperlabs.io/casper-network/casper-node/8394/1/4).  Log dump can be fetched via curl -O https://s3.us-east-2.amazonaws.com/nctl.casperlabs.io/nightly-logs/8394_nctl_dump.tar.gz
Assignee: me

### PR DESCRIPTION
**Pull request by Fraser999**
This PR fixes an issue whereby a node in `Validate` mode will not revert to `KeepUp` or `CatchUp` if it falls behind the objective tip of the chain.

After initially transitioning to `Validate` having spent a while doing the initial sync, the node could be well behind the objective tip.  In the likely case that its highest complete block is not a switch block, it would effectively be stuck waiting to produce a switch block before re-evaluating whether it should remain in `Validate` mode.  This switch block will never be created as it's fallen behind its peers and does nothing else to rectify that in `Validate` mode.

The fix is to query the `BlockAccumulator` as it does when in `KeepUp` mode.

The `ValidateInstruction::NonSwitchBlock` is also removed as it was just a special case of `ValidateInstruction::CheckLater`, but with no special handling of that variant.

Closes #4012.

### CODE REVIEW

File: node/src/reactor/main_reactor/validate.rs [hunk 1]
```diff
@@ -38,8 +44,23 @@ impl MainReactor {
 
         match self.storage.read_highest_complete_block() {
             Ok(Some(highest_complete_block)) => {
+                // If we're lagging behind the rest of the network, fall back out of Validate mode.
+                let sync_identifier = SyncIdentifier::LocalTip(
+                    *highest_complete_block.hash(),
+                    highest_complete_block.height(),
+                    highest_complete_block.header().era_id(),
+                );
+                match self.block_accumulator.sync_instruction(sync_identifier) {
```
Comment (rafal-ch) [inline node/src/reactor/main_reactor/validate.rs:53]: Just to be sure - for a block too old this will create the `LeapInstruction::OutsideAttemptExecutionThreshold`, which - in turn, will create `SyncInstruction::Leap`, right?

**Review by rafal-ch — APPROVED** [review]
LGTM :+1:

File: node/src/reactor/main_reactor/validate.rs (hunk 1 above)
Comment (Fraser999) [reply node/src/reactor/main_reactor/validate.rs:53]: Yes, I believe so.

**Review by real-felix — APPROVED** [review]

**Comment by Fraser999** [comment]
bors merge
