### PR TITLE
[BUGFIX] extend transaction_acceptor coverage

### LINKED ISSUE #5156: [BUG]: Incorrect Payment Deduction in Transactions
### Category

Bug/Issue

### Your email address

jiuhong@casper.network

### Integration Project Name(Optional)

_No response_

### Casper Network

Devnet

### Node Functionality

Node

### Description

Transactions in the Casper Network are expected to deduct the `baseline_motes_amount` set in the chainspec configuration. 

However, the observed behaviour shows that when setting the payment amount to 1 mote, the actual deducted amount remains 1 mote instead of the expected 2,500,000,000 motes.

Environment Details:

Casper Node Version: `dev 1d362cd8260b1b862f8d63ab1bd9de2f09da69f2`

Chain Name: `casper-test-jh`

Chainspec Setting: `baseline_motes_amount = 2_500_000_000`

Transaction Execution Info:
```
"limit": "1",
"consumed": "0",
"cost": "2500000000"
```

Steps to Reproduce:

Test Case 1: Transaction with 1 Mote Payment

Step 1: Check Initial Balance

```
{
    "id": 1,
    "jsonrpc": "2.0",
    "method": "query_balance",
    "params": {
        "purse_identifier": {
            "main_purse_under_public_key": "01893e2a6a50bd5e837e7685561e06a747c4df1a43caf077f01bc6ddb8db861726"
        }
    }
}
```

Response:

```
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
        "api_version": "2.0.0",
        "balance": "99999998967821101169"
    }
}
```
Step 2: Execute Transaction

```
./casper-client put-transaction package-name \
--transaction-package-name "my_hash" \
--chain-name casper-test-jh \
-n http://172.31.30.160:7777 \
--session-entry-point apple \
--gas-price-tolerance 2 \
--pricing-mode classic \
--payment-amount 1 \
--standard-payment true \
--secret-key /home/ubuntu/mywork/mycontract_condor/secret_key.pem
```

Step 3: Check Balance After Transaction
```
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
        "api_version": "2.0.0",
        "balance": "99999998967821101168"
    }
}
```

Observed Issue:

Expected deduction: 2,500,000,000 motes

Actual deduction: 1 mote

Unexpected Behavior: The balance was reduced only by 1 mote instead of the expected transaction cost.

Test Case 2: Transaction with 100 Motes Payment

Step 1: Execute Transaction

```
./casper-client put-transaction package-name \
--transaction-package-name "my_hash" \
--chain-name casper-test-jh \
-n http://172.31.30.160:7777 \
--session-entry-point apple \
--gas-price-tolerance 2 \
--pricing-mode classic \
--payment-amount 100 \
--standard-payment true \
--secret-key /home/ubuntu/mywork/mycontract_condor/secret_key.pem
```

Step 2: Check Balance After Transaction

```
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
        "api_version": "2.0.0",
        "balance": "99999998967821101167"
    }
}
```

Observed Issue:

Expected deduction: 2,500,000,000 motes

Actual deduction: 1 mote again

Refund noted: 99 motes

Additional Observations:

Pricing Mode: PaymentLimited

Initiator Public Key: 01893e2a6a50bd5e837e7685561e06a747c4df1a43caf077f01bc6ddb8db861726

Transaction Hash: b141fca79b1569cbc495d242d7203eb7bc7b44ac40bda10ed32d1eba99c3b0cf

Execution Result:

```
"current_price": 1,
"limit": "1",
"consumed": "0",
"cost": "2500000000"
```

### Date Issue Began(optional)

13/03/2025

### Attachments (optional)

_No response_

### PR DESCRIPTION
**Pull request by EdHastingsCasperAssociation**
This PR handles rejecting insufficient payment for non-native txn's

### CODE REVIEW

File: types/src/transaction/deploy.rs [hunk 1]
```diff
@@ -732,6 +750,55 @@ impl Deploy {
...
+            payment,
+            session,
+            &secret_key,
+            None,
+        )
+    }
+
+    /// Returns a random invalid `Deploy` with insufficient payment amount.
+    #[cfg(any(all(feature = "std", feature = "testing"), test))]
+    pub fn random_with_insufficient_payment_amount(
```
Comment (zajko) [inline types/src/transaction/deploy.rs:788]: Is this used?

**Review by zajko — APPROVED** [review]
