### PR TITLE
Fix handling of delegators in `global-state-update-gen`

### LINKED ISSUE #3213: global-state-update-gen should handle delegators properly when updating the validators set
Currently if the stake of a validator is being updated using the tool, the validator will lose all of its delegators during the upgrade. At the very least, it should keep its delegators if it had any, and it should be made possible to specify any changes to the set of delegators if needed.

### PR DESCRIPTION
**Pull request by fizyk20**
It is now possible to specify the delegators for new validators, and to leave delegators of old validators untouched.

The PR also fixes a couple of bugs, most notably that validators weren't being added in updates with `only_listed_validators = false`.

Closes #3213

### CODE REVIEW

File: utils/global-state-update-gen/src/generic/config.rs [hunk 1]
```diff
@@ -23,5 +25,27 @@ pub struct Transfer {
 pub struct AccountConfig {
     pub public_key: PublicKey,
     pub balance: Option<U512>,
```
Comment (goral09) [inline utils/global-state-update-gen/src/generic/config.rs:29]: What would a `None` mean here? Would we still create an account?

File: utils/global-state-update-gen/src/generic/config.rs [hunk 2]
```diff
@@ -23,5 +25,27 @@ pub struct Transfer {
...
-    pub stake: Option<U512>,
+    pub validator: Option<ValidatorConfig>,
+}
+
+#[derive(Debug, Clone, Serialize, Deserialize)]
+pub struct ValidatorConfig {
+    pub bonded_amount: U512,
+    pub delegation_rate: u8,
+    pub delegators: Vec<DelegatorConfig>,
+}
```
Comment (goral09) [inline utils/global-state-update-gen/src/generic/config.rs:38]: It would be nice to have a test that uses a `*.toml` file as an input and verifies this.

File: utils/global-state-update-gen/src/generic/config.rs [hunk 3]
```diff
@@ -31,16 +31,18 @@ pub struct AccountConfig {
 #[derive(Debug, Clone, Serialize, Deserialize)]
 pub struct ValidatorConfig {
     pub bonded_amount: U512,
-    pub delegation_rate: u8,
-    pub delegators: Vec<DelegatorConfig>,
+    pub delegation_rate: Option<u8>,
```
Comment (goral09) [inline utils/global-state-update-gen/src/generic/config.rs:36]: Shouldn't this be a required field? I don't think you can create a validator on MainNet without this.

File: utils/global-state-update-gen/src/generic.rs [hunk 4]
```diff
@@ -144,8 +144,8 @@ fn gen_snapshot_only_listed(
         };
         let seigniorage_recipient = SeigniorageRecipient::new(
             validator_cfg.bonded_amount,
-            validator_cfg.delegation_rate,
-            validator_cfg.delegators_map(),
+            validator_cfg.delegation_rate.unwrap_or_default(),
```
Comment (goral09) [inline utils/global-state-update-gen/src/generic.rs:150]: So we default to `delegation_rate = 0`?

File: utils/global-state-update-gen/src/generic.rs [hunk 5]
```diff
@@ -177,8 +177,12 @@ fn gen_snapshot_from_old(
             Some(validator) => {
                 *recipient = SeigniorageRecipient::new(
                     validator.bonded_amount,
-                    validator.delegation_rate,
-                    validator.delegators_map(),
+                    validator
+                        .delegation_rate
+                        .unwrap_or(*recipient.delegation_rate()),
```
Comment (goral09) [inline utils/global-state-update-gen/src/generic.rs]: I think this code would be clearer if instead of `snapshot` the variable name made it clear it's the _old snapshost_ and the `stakes_map` might overwrite it. Just by looking at these few lines it isn't exactly easy to understand why we're using `recipient.delegation_rate()` if `validator.delegation_rate` is `None`.

File: utils/global-state-update-gen/src/generic.rs [hunk 6]
```diff
@@ -177,8 +177,12 @@ fn gen_snapshot_from_old(
...
+                    validator
+                        .delegators_map()
+                        .unwrap_or_else(|| recipient.delegator_stake().clone()),
```
Comment (goral09) [inline utils/global-state-update-gen/src/generic.rs]: See above comment.

File: utils/global-state-update-gen/src/generic.rs [hunk 7]
```diff
@@ -172,22 +172,42 @@ fn gen_snapshot_from_old(
...
+                        validator.bonded_amount,
+                        validator.delegation_rate.unwrap_or_default(),
+                        validator.delegators_map().unwrap_or_default(),
+                    ),
                 );
-                true
             }
-            None => true,
-        });
+        }
```
Comment (goral09) [inline utils/global-state-update-gen/src/generic.rs:227]: Is there a function that would "zip" two collections over the set of keys and give you `Left(Option<value>)` and `Right(Option<value>)` ? That way you wouldn't have to iterate twice and it would be easier to understand.

File: utils/global-state-update-gen/src/generic.rs [hunk 8]
```diff
@@ -237,15 +237,20 @@ pub fn add_and_remove_bids<T: StateReader>(
...
     }
 
     // Refresh the bids - we modified them above.
     let bids = state.get_bids();
 
     for pub_key in to_unbid {
         if let Some(bid) = bids.get(&pub_key) {
+            for delegator in bid.delegators().values() {
+                // Burn the delegated funds of all the delegators.
+                // TBD: is that what should be happening when a validator is removed?
```
Comment (goral09) [inline utils/global-state-update-gen/src/generic.rs]: IMO funds should be returned to the delegators but we need to decide before merging this.

**Review by goral09 — DISMISSED** [review]
Blocking due to [`ad592a1` (#3305)](https://github.com/casper-network/casper-node/pull/3305/commits/ad592a12d1b1f7d24468e49a69998a49acf0c38c#r963552571)

File: utils/global-state-update-gen/src/generic.rs [hunk 9]
```diff
@@ -284,32 +289,93 @@ fn find_large_bids<T: StateReader>(
...
-        == Some(stake)
+        == recipient.total_stake()
     {
         // already staked the amount we need, nothing to do
         return;
     }
-    let new_bid = if let Some(bid) = state.get_bids().get(pub_key) {
-        Bid::unlocked(
+
+    let stake = *recipient.stake();
```
Comment (goral09) [inline utils/global-state-update-gen/src/generic.rs:331]: That's a _new stake_, correct?

File: utils/global-state-update-gen/src/generic.rs [hunk 10]
```diff
@@ -284,32 +289,93 @@ fn find_large_bids<T: StateReader>(
...
     pub_key: &PublicKey,
-    stake: U512,
+    recipient: &SeigniorageRecipient,
 ) {
     if state
         .get_bids()
         .get(pub_key)
         .and_then(|bid| bid.total_staked_amount().ok())
-        == Some(stake)
+        == recipient.total_stake()
```
Comment (goral09) [inline utils/global-state-update-gen/src/generic.rs]: If we change the delegators though, in such a way that the `total_stake()` doesn't change, then shouldn't we iterate over the delegators anyway?

File: utils/global-state-update-gen/src/generic/testing.rs [hunk 11]
```diff
@@ -56,14 +56,16 @@ impl MockStateReader {
 
     fn with_validators<R: Rng>(
         mut self,
-        validators: Vec<(PublicKey, U512, U512)>,
+        validators: Vec<(PublicKey, U512, ValidatorConfig)>,
```
Comment (goral09) [inline utils/global-state-update-gen/src/generic/testing.rs:61]: Isn't this basically an `AccountConfig` deconstructed?

File: utils/global-state-update-gen/src/generic.rs [hunk 12]
```diff
@@ -291,13 +291,21 @@ fn create_or_update_bid<T: StateReader>(
     pub_key: &PublicKey,
     recipient: &SeigniorageRecipient,
 ) {
+    let check_bid = |bid: &Bid| {
```
Comment (goral09) [inline utils/global-state-update-gen/src/generic.rs:309]: Can you leave a short comment what you're asserting here exactly?

File: utils/global-state-update-gen/src/generic.rs [hunk 13]
```diff
@@ -291,13 +291,21 @@ fn create_or_update_bid<T: StateReader>(
...
+            .collect();
+        &bid_delegators == recipient.delegator_stake() && *bid.staked_amount() == *recipient.stake()
+    };
     if state
         .get_bids()
         .get(pub_key)
-        .and_then(|bid| bid.total_staked_amount().ok())
-        == recipient.total_stake()
+        .map(check_bid)
+        .unwrap_or(false)
```
Comment (goral09) [inline utils/global-state-update-gen/src/generic.rs]: Isn't this equivalent to simply `state.get_bids().get(pub_key) == bid_delegators` ?

File: utils/global-state-update-gen/src/generic.rs (hunk 10 above)
Comment (goral09) [reply utils/global-state-update-gen/src/generic.rs]: I can see it being fixed in [`fa6f877` (#3305)](https://github.com/casper-network/casper-node/pull/3305/commits/fa6f877509be5454cfa2c93a0db60a0d0ca9ca7d)

File: utils/global-state-update-gen/src/generic/testing.rs [hunk 14]
```diff
@@ -560,3 +667,546 @@ fn should_replace_one_validator() {
...
+    assert_eq!(
+        result.get(&Key::Balance(delegator1_bid_purse.addr())),
+        Some(&StoredValue::from(
+            CLValue::from_t(U512::from(0)).expect("should convert U512 to CLValue")
+        ))
+    );
+
+    // 5 keys above should be all that was written
+    assert_eq!(result.len(), 5);
+}
```
Comment (goral09) [inline utils/global-state-update-gen/src/generic/testing.rs:1277]: There's A LOT of opportunities here for refactoring - creating helper functions to construct `AccountConfig`, `ValidatorConfig`, replacing things, asserting things. Currently it's very imperative and has a high cognitive load. If you simplify things into more readable representation then I'm sure people will be able to do a better review.

File: utils/global-state-update-gen/src/generic/config.rs (hunk 1 above)
Comment (fizyk20) [reply utils/global-state-update-gen/src/generic/config.rs:29]: It means that we don't want to change the existing balance. The tool supports changing just some aspects of existing accounts - like, we might want to only remove the stake of a validator, but not touch their account balance.
If the account doesn't exist and this is `None`, it won't be created.

File: utils/global-state-update-gen/src/generic/config.rs (hunk 3 above)
Comment (fizyk20) [reply utils/global-state-update-gen/src/generic/config.rs:36]: I see you resolved it, but just for the sake of anyone stumbling upon this - `None` will just mean "leave this unchanged". (Or, if there was no previous value, it would default to 0.)

File: utils/global-state-update-gen/src/generic.rs (hunk 4 above)
Comment (fizyk20) [reply utils/global-state-update-gen/src/generic.rs:150]: If it's not set explicitly and no delegation rate was already set in the global state, yes.

File: utils/global-state-update-gen/src/generic.rs (hunk 7 above)
Comment (fizyk20) [reply utils/global-state-update-gen/src/generic.rs:227]: I don't know, but it's a good idea.

File: utils/global-state-update-gen/src/generic.rs (hunk 8 above)
Comment (fizyk20) [reply utils/global-state-update-gen/src/generic.rs]: I'm actually leaning towards burning. That's because this is mostly intended to be used in cases where we _have_ to remove a validator, because it was misbehaving and was part of a problem that brought the network down. If we didn't burn delegators' stakes, the validator could defend against losing their stake after misbehaving by only staking a small amount themselves, and delegating almost all of the stake from a different account.

File: utils/global-state-update-gen/src/generic.rs (hunk 9 above)
Comment (fizyk20) [reply utils/global-state-update-gen/src/generic.rs:331]: Yes :+1:

File: utils/global-state-update-gen/src/generic/testing.rs (hunk 11 above)
Comment (fizyk20) [reply utils/global-state-update-gen/src/generic/testing.rs:61]: Almost - only the fields aren't optional.

File: utils/global-state-update-gen/src/generic.rs (hunk 8 above)
Comment (goral09) [reply utils/global-state-update-gen/src/generic.rs]: Why would delegators be punished for misbehavior of the validator they had delegated to?

File: utils/global-state-update-gen/src/generic.rs (hunk 13 above)
Comment (fizyk20) [reply utils/global-state-update-gen/src/generic.rs]: Not quite, because 1) types wouldn't check out, and 2) we're also checking the stake of the validator themselves, not only the delegators.

File: utils/global-state-update-gen/src/generic.rs (hunk 8 above)
Comment (fizyk20) [reply utils/global-state-update-gen/src/generic.rs]: Because otherwise it leaves an easy way of protecting the stake for validators that are planning to misbehave.
As in - if you stake 1000000 CSPR and misbehave, you lose 1000000 CSPR. But if you stake 100 CSPR, then delegate the remaining 999900 CSPR from a different account, your total stake in the network is the same, but if you misbehave, you only lose 100 CSPR.
But I'm not sure if that's a sufficient argument for doing that.

Comment (goral09) [reply utils/global-state-update-gen/src/generic.rs]: I understand how the malicious validators could avoid being slashed but I'm still not convinced that the cure isn't worse than disease.

Comment (fizyk20) [reply utils/global-state-update-gen/src/generic.rs]: Yeah, I'm not sure myself. I guess it could be seen as incentivizing only delegating to validators you trust, and also to validators that have high stakes themselves.

File: utils/global-state-update-gen/src/generic.rs [hunk 15]
```diff
@@ -159,23 +165,69 @@ fn gen_snapshot_from_old(
...
-            Some(stake) => {
-                *recipient =
-                    SeigniorageRecipient::new(*stake, Default::default(), Default::default());
-                true
+        // We use `retain` to drop some entries and modify some of the ones that will be retained.
+        recipients.retain(
+            |public_key, recipient| match validators_map.get(public_key) {
+                // If the validator's stake is configured to be zero, we drop them from the
+                // snapshot.
+                Some(validator) if validator.bonded_amount == U512::zero() => false,
```
Comment (afck) [inline utils/global-state-update-gen/src/generic.rs]: I think `validator.bonded_amount.is_zero()` would avoid allocating those zero bytes.

File: utils/global-state-update-gen/src/generic.rs [hunk 16]
```diff
@@ -159,23 +165,69 @@ fn gen_snapshot_from_old(
...
+                    );
+                    true
+                }
+                // Validators not present in the config will be kept unmodified.
+                None => true,
+            },
+        );
+
+        // Add the validators that weren't present in the old snapshot.
+        for (public_key, validator) in &validators_map {
```
Comment (afck) [inline utils/global-state-update-gen/src/generic.rs:210]: What if that's more than the validator slot number now?

File: utils/global-state-update-gen/src/generic.rs [hunk 17]
```diff
@@ -250,32 +302,94 @@ fn find_large_bids<T: StateReader>(
...
-        )
+            *recipient.delegation_rate(),
+        );
+
+        for (delegator_pub_key, delegator_stake) in recipient.delegator_stake() {
+            let delegator = if let Some(delegator) = old_bid.delegators().get(delegator_pub_key) {
+                Delegator::unlocked(
+                    delegator_pub_key.clone(),
+                    *delegator_stake,
+                    *delegator.bonding_purse(),
```
Comment (afck) [inline utils/global-state-update-gen/src/generic.rs:345]: Do we need to change the amount in the bonding purse here?

File: utils/global-state-update-gen/src/generic/testing.rs [hunk 18]
```diff
@@ -56,14 +56,16 @@ impl MockStateReader {
```
Comment (afck) [inline utils/global-state-update-gen/src/generic/testing.rs:58]: Should `with_account` subtract the old balance, in case `purses` already had an entry?
Alternatively, it could just panic in that case.

File: utils/global-state-update-gen/src/generic.rs (hunk 16 above)
Comment (fizyk20) [reply utils/global-state-update-gen/src/generic.rs:210]: Then the network will have more validators than there are slots for the next `auction_delay+1` eras :sweat_smile: But it will be fixed in later eras, as the validators for them will be calculated by the auction contract again.

File: utils/global-state-update-gen/src/generic.rs (hunk 17 above)
Comment (fizyk20) [reply utils/global-state-update-gen/src/generic.rs:345]: The call to `set_bid` at the end of the function will take care of that. This part just generates the updated bid, `set_bid` makes sure that all the other data is consistent with the bid that is being set.

File: utils/global-state-update-gen/src/generic/testing.rs (hunk 18 above)
Comment (fizyk20) [reply utils/global-state-update-gen/src/generic/testing.rs:58]: That would mean we randomly generated the same hash twice, though. Should we be guarding against such unlikely collisions?

Comment (fizyk20) [reply utils/global-state-update-gen/src/generic/testing.rs:58]: Unless you meant `accounts` having an entry, in case we call the function with the same account hash twice. I'd see that as programmer error, in which case panicking is probably the better choice :+1:

Comment (afck) [reply utils/global-state-update-gen/src/generic/testing.rs:58]: Ah, right! Yes, for `accounts` it would probably make sense to panic. (Not a blocker, of course!)

**Review by afck — APPROVED** [review]

File: utils/global-state-update-gen/src/generic/testing.rs [hunk 19]
```diff
@@ -570,6 +570,104 @@ fn should_replace_one_validator() {
...
+
+    // we'll be updating the validators set to only contain validator2
+    let config = Config {
+        accounts: vec![AccountConfig {
+            public_key: validator2.clone(),
+            balance: Some(U512::from(102)),
+            validator: Some(ValidatorConfig {
+                bonded_amount: U512::from(102),
+                delegation_rate: None,
+                delegators: None,
```
Comment (afck) [inline utils/global-state-update-gen/src/generic/testing.rs]: Maybe also use `default()` here, or `None` above for validator 1, just be be consistent.

File: utils/global-state-update-gen/src/generic/testing.rs [hunk 20]
```diff
@@ -849,6 +947,103 @@ fn should_replace_a_delegator() {
...
+        }],
+        only_listed_validators: false,
+        slash_instead_of_unbonding: false,
+        ..Default::default()
+    };
+
+    let update = get_update(&mut reader, config);
+
+    update.assert_seigniorage_recipients_written(&mut reader);
+    update.assert_total_supply(&mut reader, 229);
```
Comment (afck) [inline utils/global-state-update-gen/src/generic/testing.rs:995]: Just to make sure I understand correctly: The total supply before the update was 215, right?

**Review by afck — APPROVED** [review]

File: utils/global-state-update-gen/src/generic/testing.rs (hunk 20 above)
Comment (fizyk20) [reply utils/global-state-update-gen/src/generic/testing.rs:995]: Right :+1:

**Comment by fizyk20** [comment]
bors merge

**Comment by fizyk20** [comment]
bors merge
