### PR TITLE
Avoid setting `shared_pre_state` to old state

### LINKED ISSUE #3975: Investigate nightly test failure
network_soundness.py test failed in [this run](https://drone-auto-casper-network.casperlabs.io/casper-network/casper-node/8307), apparently with a restarted node failing to keep up with the rest of the network.

### PR DESCRIPTION
**Pull request by Fraser999**
This PR fixes a race condition whereby a higher `shared_pre_state` in contract runtime set via `set_initial_state` (e.g. after receiving a sync leap) could be overwritten by a lower one if the node was in the middle of executing an older block when the shared pre-state was set.

Closes #3975.

### CODE REVIEW

File: node/src/components/contract_runtime.rs [hunk 1]
```diff
@@ -768,16 +772,28 @@ impl ContractRuntime {
...
+            // which completed execution just after this to set the `shared_pre_state` back to an
+            // earlier block height.
+            let mut shared_pre_state = shared_pre_state.lock().unwrap();
+            if shared_pre_state.next_block_height < new_execution_pre_state.next_block_height {
+                debug!(
+                    next_block_height = new_execution_pre_state.next_block_height,
+                    "ContractRuntime: updating new_execution_pre_state",
+                );
+                *shared_pre_state = new_execution_pre_state.clone();
+                debug!("ContractRuntime: updated new_execution_pre_state");
```
Comment (rafal-ch) [inline node/src/components/contract_runtime.rs]: Maybe one of these two similar `debug!` messages is redundant?
Also, wdyt about logging a message in case we detect the incorrect attempt to update execution state?

File: node/src/components/contract_runtime/config.rs [hunk 2]
```diff
@@ -29,7 +29,7 @@ pub struct Config {
     pub max_query_depth: Option<u64>,
     /// Enable synchronizing to disk only after each block is written.
     ///
-    /// Defaults to `false`.
+    /// Defaults to `true`.
```
Comment (rafal-ch) [inline node/src/components/contract_runtime/config.rs:32]: Nice one :)

**Review by rafal-ch — APPROVED** [review]
LGTM :+1: 

No blockers.

File: node/src/components/contract_runtime.rs (hunk 1 above)
Comment (Fraser999) [reply node/src/components/contract_runtime.rs]: I'm happy to remove one.  I'll remove the second one as it has less info.

Likewise, happy to add a debug message in an `else` arm.

Comment (Fraser999) [reply node/src/components/contract_runtime.rs]: Fixed in [d24efc4](https://github.com/casper-network/casper-node/pull/3989/commits/d24efc48572d1701cbe4766ca8e71881a36a7bc8).

File: node/src/components/contract_runtime/tests.rs [hunk 3]
```diff
@@ -0,0 +1,389 @@
...
+    )
+}
+
+/// A function to be used a condition check, indicating that execution has completed.
+fn execution_completed(event: &Event) -> bool {
+    matches!(event, Event::MetaBlockAnnouncement(_))
+}
+
+#[tokio::test]
+async fn should_not_set_shared_pre_state_to_lower_block_height() {
```
Comment (alsrdn) [inline node/src/components/contract_runtime/tests.rs:200]: 👍 awesome

**Review by alsrdn — APPROVED** [review]
Nice find! LGTM!

**Review by georgepisaltu — APPROVED** [review]
LGTM

**Comment by Fraser999** [comment]
bors merge
