### PR TITLE
Issue 2047 asymmetric type from hex

### LINKED ISSUE #2047: Fix AsymmetricType::from_hex for system variant
Should be updated to
```rust
match tag[0] {
    SYSTEM_TAG => {
        if key_bytes.is_empty() {
            return Ok(Self::system());
        }
        Err(Error::AsymmetricKey(format!("failed to decode from hex: invalid system variant")))
    }
    ED25519_TAG => {
        let bytes = hex::decode(key_bytes)?;
        Self::ed25519_from_bytes(&bytes)
    }
    SECP256K1_TAG => {
        let bytes = hex::decode(key_bytes)?;
        Self::secp256k1_from_bytes(&bytes)
    }
    _ => Err(Error::AsymmetricKey(format!(
        "failed to decode from hex: invalid tag: expected {} or {}, got {}",
        ED25519_TAG, SECP256K1_TAG, tag[0]
    ))),
}

```
and tests added

### PR DESCRIPTION
**Pull request by luis-casper**
Fully addresses the following issue:
https://app.zenhub.com/workspaces/engineering-60953fafb1945f0011a3592d/issues/casper-network/casper-node/2047

### CODE REVIEW

File: types/src/crypto/asymmetric_key.rs [hunk 1]
```diff
@@ -743,3 +749,104 @@ mod detail {
...
+
+        #[test]
+        fn too_short() {
+            assert!(PublicKey::from_hex([0u8; 0]).is_err());
+            assert!(PublicKey::from_hex([0u8; 1]).is_err());
+        }
+
+        // The following atrocity is due to the crates `rand_core` and
+        // `k256::elliptic_curve::rand_core` not necessarily being the same.
+        mod myrng {
```
Comment (xcthulhu) [inline types/src/crypto/asymmetric_key.rs]: Maybe use a [proptest][1] instead of this? We already have `crate::crypto::assymetric_key::public_key_arb()`...

[1]: https://docs.rs/proptest/1.0.0/proptest/

Comment (luis-casper) [reply types/src/crypto/asymmetric_key.rs]: That's an awesome review and I learned a lot, thanks.
I think I should start over with a new PR.

Comment (luis-casper) [reply types/src/crypto/asymmetric_key.rs]: I backtracked this PR and added new commits from the start.

**Review by xcthulhu — APPROVED** [review]
LGTM

**Comment by luis-casper** [comment]
bors merge

**Review by Fraser999 — APPROVED** [review]

**Review by Fraser999 — APPROVED** [review]

**Review by Fraser999 — DISMISSED** [review]
After further discussion, I think we should revert the behaviour of `AsymmetricType::from_hex()` so that it remains an error to try to parse a system key/sig from hex.  There doesn't appear to be a valid use-case for such functionality.

Let's keep the additional tests added in this PR, but update them as required to match the original behaviour.

**Comment by xcthulhu** [comment]
>After further discussion, I think we should revert the behaviour of AsymmetricType::from_hex() so that it remains an error to try to parse a system key/sig from hex. There doesn't appear to be a valid use-case for such functionality.

@Fraser999 So actually 🤓  we may need this for `fast-sync`.  There's some parts here you know better than I, though. 

In the fast sync branch we make a switch block after each upgrade.  The block proposer for that block is the system contract.  I don't know the client code that well.  Will it be the case that the client will need to parse the hex for the system contract?  Perhaps there is some other encoding it uses...

**Comment by luis-casper** [comment]
> After further discussion, I think we should revert the behaviour of `AsymmetricType::from_hex()` so that it remains an error to try to parse a system key/sig from hex. There doesn't appear to be a valid use-case for such functionality.
> 
> Let's keep the additional tests added in this PR, but update them as required to match the original behaviour.

Done.

File: types/src/crypto/asymmetric_key.rs [hunk 2]
```diff
@@ -81,17 +81,20 @@ where
...
 
-        let tag = checksummed_hex::decode(&tag_bytes)?;
-        let key_bytes = checksummed_hex::decode(&key_bytes)?;
+        let tag = checksummed_hex::decode(&tag_hex)?;
+        let key_bytes = checksummed_hex::decode(&key_hex)?;
 
         match tag[0] {
+            SYSTEM_TAG => Err(Error::AsymmetricKey(
+                "failed to decode from hex: cannot decode system variant".to_string(),
+            )),
```
Comment (goral09) [inline types/src/crypto/asymmetric_key.rs]: I think we should allow this. If someone tries to use the system key, as a _signing key_, then it should fail on signature validation later. In Ethereum, a common practice for burning tokens is to send them to an address that no key exists for - 0x00000... I don't see a reason with using it in other contexts (like an argument).

**Comment by afck** [comment]
Yes, for fast sync we need to decide how we handle the automatic switch block. In the current implementation [its proposer is `PublicKey::System`](https://github.com/casper-network/casper-node/blob/be209cb863a911d3b5f590bf762a99acd637a17f/node/src/reactor/participating.rs#L649). An alternative would be to introduce a new special public key value instead. :confused:

**Comment by luis-casper** [comment]
Even though we might drop this one, I've left it complete in a usable state.

**Review by Fraser999 — APPROVED** [review]

**Review by goral09 — APPROVED** [review]
