### PR TITLE
Fix emergency upgrade tests

### LINKED ISSUE #3503: Fix emergency_upgrade_test_balances.sh
it fails with ShutdownForUpgrade: validator_weights cannot be missing

https://casperlabs-team.slack.com/archives/C01ULKL8G8J/p1671086114124359

### PR DESCRIPTION
**Pull request by fizyk20**
This fixes some bugs related to emergency upgrades and allows the related tests to pass again.

Closes #3503

### CODE REVIEW

File: node/src/components/storage.rs [hunk 1]
```diff
@@ -1907,10 +1907,26 @@ impl Storage {
...
+        if utils::check_sufficient_block_signatures(
+            next_era_validator_weights,
+            self.fault_tolerance_fraction,
+            Some(&highest_signed_block_header.block_signatures),
+        )
+        .is_ok()
+        {
+            result.push(highest_signed_block_header.clone());
+        } else {
+            return Ok(Some(result));
```
Comment (Fraser999) [inline node/src/components/storage.rs]:
```suggestion
```

**Review by Fraser999 — DISMISSED** [review]
One tiny nitpick, certainly not a blocker!

File: node/src/reactor.rs [hunk 2]
```diff
@@ -925,54 +925,13 @@ where
...
-                            .announce_block_peer_with_justification(
-                                sender,
-                                BlocklistJustification::SentBadDeploy { error },
-                            )
-                            .ignore();
-                    }
-                };
-            <R as Reactor>::dispatch_event(reactor, effect_builder, rng, event)
-        }
+        NetResponse::Deploy(ref serialized_item) => handle_fetch_response::<R, Deploy>(
```
Comment (alsrdn) [inline node/src/reactor.rs:927]: Since the deploy doesn't go through the `DeployAcceptor` anymore, I don't think it gets validated. Does it need to get validated at this point?

Comment (Fraser999) [reply node/src/reactor.rs:927]: The `Deploy` gets minimal validation done by the fetcher (see `impl FetcherItem for Deploy`) when it arrives, so in this case where we've explicitly asked for this Deploy, we don't need (or want) to run the more comprehensive validation done by the `DeployAcceptor`.

Comment (alsrdn) [reply node/src/reactor.rs:927]: And also should we maybe get rid of the `Source::Peer(_)` machinery in `DeployAcceptor::handle_put_to_storage()` in this case?

Comment (Fraser999) [reply node/src/reactor.rs:927]: Well, that's the appropriate source variant when we get a deploy gossiped to us - that flow still goes via the deploy acceptor.

File: node/src/components/storage.rs (hunk 1 above)
Comment (fizyk20) [reply node/src/components/storage.rs]: Oh :man_facepalming: Yeah, that's definitely a good call :sweat_smile:

File: node/src/reactor.rs (hunk 2 above)
Comment (alsrdn) [reply node/src/reactor.rs:927]: I think we can look at using `Source::PeerGossiped` in that case, but certainly not the scope of this PR.

**Review by alsrdn — APPROVED** [review]
LGTM

**Review by georgepisaltu — APPROVED** [review]

**Comment by fizyk20** [comment]
bors merge
