### PR TITLE
Fix wrong state hash being passed to the contract runtime

### LINKED ISSUE #1761: Emergency upgrade test failing
The emergency upgrade test is failing on CI on commit 487078483a4b5dd93d7fb0fce54c43869632c970

### PR DESCRIPTION
**Pull request by fizyk20**
A recent refactoring of the contract runtime made a slight change to one piece of functionality related to upgrades, which was making sure that blocks created after the upgrade use the state hash that was the result of applying the upgrade to the last pre-upgrade block, instead of the hash from that block. This introduced a bug, which this PR fixes.

Closes #1761

### CODE REVIEW

**Review by afck — APPROVED** [review]

File: node/src/reactor/participating.rs [hunk 1]
```diff
@@ -476,10 +476,18 @@ impl reactor::Reactor for Reactor {
...
-        contract_runtime.set_initial_state(maybe_latest_block_header.map_or_else(
-            || chainspec_loader.initial_execution_pre_state(),
-            |latest_block_header| ExecutionPreState::from(&latest_block_header),
-        ));
+        let execution_pre_state = match maybe_latest_block_header {
+            Some(latest_block_header)
+                if chainspec_loader
+                    .initial_execution_pre_state()
+                    .next_block_height()
+                    <= latest_block_header.height() =>
```
Comment (goral09) [inline node/src/reactor/participating.rs:484]: I think there should be a `chainspec_loader.after_upgrade()` endpoint now that returns `true` only if we've just gone through an upgrade and there are no more blocks in the storage.

**Review by goral09 — APPROVED** [review]

**Review by xcthulhu — APPROVED** [review]

File: node/src/reactor/participating.rs (hunk 1 above)
Comment (fizyk20) [reply node/src/reactor/participating.rs:484]: I think that would require us to store more state in the chainspec loader, wouldn't it? We'd have to store the "we've just gone through an upgrade in this run" bit of information. And then this `after_upgrade()` method would have to send a request to storage, so it would complicate this part of code quite significantly (one more effect-event round-trip).

I'm not totally opposed to the idea, but I think it's probably more complicated than it might look at the first glance.

**Comment by fizyk20** [comment]
bors merge

File: node/src/reactor/participating.rs (hunk 1 above)
Comment (goral09) [reply node/src/reactor/participating.rs:484]: > I think that would require us to store more state in the chainspec loader, wouldn't it? We'd have to store the "we've just gone through an upgrade in this run" bit of information. 

I'm sorry, I wasn't totally clear. I meant that we already do that - there already is `after_upgrade()` method in the chainspec loader and it does read the storage to determine it.
