### PR TITLE
Make the number of blocks to consider configurable in the chainspec

### LINKED ISSUE #4427: Investigate rewards consensus potential bug
Bart is already investigating this potential bug

Network: 100  + 20
Name: ajith-dev-big (16s)
Branch: dev
Config: '{"config":{}, "chainspec":{"era_duration": \"15minutes\","block_max_transfer_count": 650, "block_max_deploy_count": 35, "block_max_approval_count": 1300 }}'
Test: Validator Reward Impact Evaluation with multiple slow Validators
Run01: Commit: cb968e5c74a64fc5c0bc8c2499271f7b2dcbd41f (enabled fail-point and merged PR#4386 ) with no load
Observations:
5 validators was set with fail-point consensus.message_delay=8000  and consensus.message_delay=11000
5 validators slowing slow-down as higher finalisation times ~19s to 23s
the network round time increased to 32s twice but not for a complete era (15mins)
nodes were set with fail-point around Era 19 switchblock
Era 20 - 32s for ~3mins
Era 22 - 32s for ~6mins
attached the consensus dumps for reference.
the healthy validator rewards shown to be slightly impacted and then stabilizes
Dumps: http://genesis.casperlabs.io/ajith-dev-big/casper-node-dumps/ajith-dev-big/21112023_0520/dump_download_list.html

### PR DESCRIPTION
**Pull request by fizyk20**
This adds a chainspec setting for the number of recent blocks taken into account by `PerformanceMeter` when measuring performance and sets it to 10 by default.

The era lengths in slow node nightly tests are also increased in order to give the nodes a chance to slow down within an era.

Closes #4427

### CODE REVIEW

**Review by Fraser999 — COMMENTED** [review]
LGTM, but we should probably have a changelog entry for this.

**Review by Fraser999 — APPROVED** [review]

File: node/src/types/chainspec/highway_config.rs [hunk 1]
```diff
@@ -59,22 +73,29 @@ impl ToBytes for HighwayConfig {
         let mut buffer = bytesrepr::allocate_buffer(self)?;
         buffer.extend(self.maximum_round_length.to_bytes()?);
         buffer.extend(self.reduced_reward_multiplier.to_bytes()?);
+        buffer.extend(self.performance_meter.blocks_to_consider.to_bytes()?);
```
Comment (rafal-ch) [inline node/src/types/chainspec/highway_config.rs:76]: A nit:
Maybe this should be just 
```suggestion
        buffer.extend(self.performance_meter.to_bytes()?);
```
with a proper `bytesrepr` implementation for `PerformanceMeterConfig`?

File: node/src/components/consensus/protocols/highway/performance_meter.rs [hunk 2]
```diff
@@ -5,20 +5,21 @@ use tracing::error;
...
     },
-    traits::Context,
-    utils::ValidatorIndex,
+    types::chainspec::PerformanceMeterConfig,
 };
 
-/// The number of most recent blocks for which we average the max quorum in which we participated.
-const BLOCKS_TO_CONSIDER: usize = 5;
 /// The average max quorum that triggers us to slow down: with this big or smaller average max
 /// quorum per `BLOCKS_TO_CONSIDER`, we increase our round length.
```
Comment (rafal-ch) [inline node/src/components/consensus/protocols/highway/performance_meter.rs]: Please update the comments to not mention `BLOCKS_TO_CONSIDER` (I think there are more that just this one).

**Review by rafal-ch — APPROVED** [review]
LGTM :+1: 

Some nits, but no blockers

File: node/src/types/chainspec/highway_config.rs (hunk 1 above)
Comment (fizyk20) [reply node/src/types/chainspec/highway_config.rs:76]: I'm not sure if this is worth it when it's just the one field - but I'd definitely support this way of doing it with more than one field.
