### PR TITLE
Fix unbonding purses serialization

### LINKED ISSUE #2964: Fix deserialization of legacy UnbondingPurses in storage
The `UnbondingPurse` type had a new field `new_validator: Option<PublicKey>` added in recent changes.  The old version of this type has already been stored in the storage DB as part of `ExecutionResult`s (deploy metadata).  If we try to parse the old encoded data using the new struct's method, we usually get a failure.

### PR DESCRIPTION
**Pull request by rafal-ch**
This PR makes the `Storage` component aware that the `UnbondingPurses` struct has two different flavors:
1) Legacy one, i.e. without the `new_validator` field
2) Extended one, i.e. with the `new_validator` field

When retrieving the `UnbondingPurses` from DB, the `Storage` will always return the extended `UnbondingPurses` providing the conversion from the legacy struct on the fly, setting the `new_validator` field to `None`.

Closes #2964

### CODE REVIEW

File: node/src/components/storage/lmdb_ext.rs [hunk 1]
```diff
@@ -211,12 +240,54 @@ pub(super) fn deserialize<T: DeserializeOwned>(raw: &[u8]) -> Result<T, LmdbExtE
...
+        let upgraded_unbonding_purse = UnbondingPurse::new(
+            deserialized.bonding_purse,
+            deserialized.validator_public_key,
+            deserialized.unbonder_public_key,
+            deserialized.era_of_creation,
+            deserialized.amount,
+            Option::default(),
+        );
+        let raw = bincode::serialize(&upgraded_unbonding_purse).unwrap();
+        bincode::deserialize(&raw).map_err(|err| LmdbExtError::DataCorrupted(Box::new(err)))
```
Comment (rafal-ch) [inline node/src/components/storage/lmdb_ext.rs]: Note to self:
This roundtrip should go away.

File: node/src/components/storage/lmdb_ext.rs [hunk 2]
```diff
@@ -211,12 +240,54 @@ pub(super) fn deserialize<T: DeserializeOwned>(raw: &[u8]) -> Result<T, LmdbExtE
...
+    } else {
+        deserialize(&raw[UNBONDING_PURSE_V2_MAGIC_BYTES.len()..])
+    }
```
Comment (Fraser999) [inline node/src/components/storage/lmdb_ext.rs]: I had this idea to get round the double deserialize issue:
```suggestion
    const BINCODE_ENCODED_NONE: [u8; 4] = [0; 4];
    if is_legacy(raw) {
        deserialize(&[raw, &BINCODE_ENCODED_NONE].concat())
    } else {
        deserialize(&raw[UNBONDING_PURSE_V2_MAGIC_BYTES.len()..])
    }
```

File: node/src/components/storage/tests.rs [hunk 3]
```diff
@@ -2071,3 +2074,55 @@ fn should_get_block_header_by_height() {
...
+#[test]
+fn should_read_legacy_unbonding_purse() {
+    // These bytes represent the `UnbondingPurse` struct with the `new_validator` field removed
+    // and serialized with `bincode`.
+    // In theory, we can generate these bytes by serializing the `WithdrawPurse`, but at some point,
+    // these two structs may diverge and it's a safe bet to rely on the bytes
+    // that are consistent with what we keep in the current storage.
+    const LEGACY_BYTES: &str = "0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e07010000002000000000000000197f6b23e16c8532c6abc838facd5ea789be0c76b2920334039bfa8b3d368d610100000020000000000000004508a07aa941707f3eb2db94c8897a80b2c1197476b6de213ac273df7d86c4ffffffffffffffffff40feffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff";
+
+    let decoded = hex::decode(LEGACY_BYTES).expect("decode");
```
Comment (Fraser999) [inline node/src/components/storage/tests.rs]: We normally use the `base16` crate for this - that will avoid you importing `uint::hex`.

File: node/src/components/storage/lmdb_ext.rs (hunk 2 above)
Comment (rafal-ch) [reply node/src/components/storage/lmdb_ext.rs]: Nice one! :+1: 
Fixed in fa65259d147e1213322d2c4638e7328a26f305d1

File: node/src/components/storage/lmdb_ext.rs (hunk 1 above)
Comment (rafal-ch) [reply node/src/components/storage/lmdb_ext.rs]: It's gone thanks to https://github.com/casper-network/casper-node/pull/2967#discussion_r866926169

File: node/src/components/storage/tests.rs (hunk 3 above)
Comment (rafal-ch) [reply node/src/components/storage/tests.rs]: Fixed in 0c32238bf66d3d14721e45c9c88d31073af8e9c3

File: node/src/components/storage/lmdb_ext.rs [hunk 4]
```diff
@@ -10,11 +10,18 @@
...
 use serde::{de::DeserializeOwned, Serialize};
 use thiserror::Error;
 
-use casper_types::bytesrepr::{self, FromBytes, ToBytes};
+use casper_types::{
+    bytesrepr::{self, FromBytes, ToBytes},
+    system::auction::UnbondingPurse,
+};
+
+const UNBONDING_PURSE_V2_MAGIC_BYTES: &[u8] = &[121, 17, 133, 179, 91, 63, 69, 222];
```
Comment (afck) [inline node/src/components/storage/lmdb_ext.rs:24]: Is there a reason why a serialized V1 purse can never start with those bytes?

**Review by afck — APPROVED** [review]

File: node/src/components/storage/lmdb_ext.rs (hunk 4 above)
Comment (rafal-ch) [reply node/src/components/storage/lmdb_ext.rs:24]: Unfortunately not.
The `UnbondingPurse` starts with an `URef`, which starts with an `URefAddr`, which is just a `[u8; 32]` that could be anything.
I used 8 magic bytes as an effort to minimize the chances for a collision.

**Review by Fraser999 — APPROVED** [review]

File: node/src/components/storage/lmdb_ext.rs [hunk 5]
```diff
@@ -211,12 +247,47 @@ pub(super) fn deserialize<T: DeserializeOwned>(raw: &[u8]) -> Result<T, LmdbExtE
...
+/// bytes that represent the `None` serialized with `bincode` - these bytes simulate
+/// the existence of the `new_validator` field added to the `UnbondingPurse` struct.
+pub(super) fn deserialize_unbonding_purse<T: DeserializeOwned>(
+    raw: &[u8],
+) -> Result<T, LmdbExtError> {
+    const BINCODE_ENCODED_NONE: [u8; 4] = [0; 4];
+    if is_legacy(raw) {
+        deserialize(&[raw, &BINCODE_ENCODED_NONE].concat())
+    } else {
+        deserialize(&raw[UNBONDING_PURSE_V2_MAGIC_BYTES.len()..])
```
Comment (mpapierski) [inline node/src/components/storage/lmdb_ext.rs:270]: ~~This will panic if `raw.len() < UNBONDING_PURSE_V2_MAGIC_BYTES.len()`~~ if `is_legacy` returns false then `raw.len() >= UNBONDING_PURSE_V2_MAGIC_BYTES.len()`

File: node/src/components/storage/lmdb_ext.rs [hunk 6]
```diff
@@ -157,15 +164,44 @@ where
...
+) -> Result<Vec<u8>, LmdbExtError> {
+    let buffer = if TypeId::of::<UnbondingPurse>() == TypeId::of::<V>() {
+        serialize_unbonding_purse(value)?
+    } else {
+        serialize(value)?
+    };
+    Ok(buffer)
+}
+
+/// Deerializes an object from the raw bytes.
```
Comment (mpapierski) [inline node/src/components/storage/lmdb_ext.rs]:
```suggestion
/// Deserializes an object from the raw bytes.
```

Comment (rafal-ch) [reply node/src/components/storage/lmdb_ext.rs]: Resolved in 8100ff7148b1f8eb4dd55aef8f878be2995bbdc9
