### PR TITLE
Revert keeping zero bids in the auction state

### LINKED ISSUE #4808: SRE Testing: Failed to start network with Mainnet DB snapshot
Please refer to the slack conversation [here](https://casper-labs-team.slack.com/archives/C01ULKL8G8J/p1720821743218009)

### PR DESCRIPTION
**Pull request by fizyk20**
This reverts the changes introduced in #4719, as they are no longer needed since #4728 got merged and they were the reason behind the recent issues in tests.

Since the logic introduced in #4719 expected zero bids to exist until the unbonds are processed, and 1.5 removed them upon bid withdrawal / undelegation, this caused issues during the upgrade: 2.0 was attempting to remove zero bids which had already been removed, and failing with a `ValidatorNotFound` error. Thus, the simplest fix was to revert those changes.

This PR also adds a few debug messages that proved to be useful in figuring out this issue.

Closes #4808, #4811, #4812

### CODE REVIEW

File: node/src/reactor/main_reactor/keep_up.rs [hunk 1]
```diff
@@ -647,13 +648,19 @@ impl MainReactor {
...
+                "checking max ttl");
             let max_ttl: MaxTtl = self.chainspec.transaction_config.max_ttl.into();
             if max_ttl.synced_to_ttl(
                 highest_switch_block_header.timestamp(),
                 highest_orphaned_block_header,
             ) {
+                debug!("is synced to ttl");
                 return Ok(Some(SyncBackInstruction::TtlSynced));
             }
+            debug!("is not synced to ttl");
```
Comment (alsrdn) [inline node/src/reactor/main_reactor/keep_up.rs]: I guess we don't need this debug message since we do log when we're finally synced and we also log each time we check the TTL. I fear this is a bit too spammy.

**Review by alsrdn — APPROVED** [review]

**Review by darthsiroftardis — APPROVED** [review]

File: node/src/reactor/main_reactor/keep_up.rs (hunk 1 above)
Comment (fizyk20) [reply node/src/reactor/main_reactor/keep_up.rs]: Fair. I might have gone slightly overboard with the messages, when I got a bit confused by what was happening.
