### PR TITLE
Fix too many bids being removed when generating a global state update

### LINKED ISSUE #2736: specific emergency upgrade scenario issue
Log Dumps: http://genesis.casperlabs.io/rti-fast-sync/casper-node-dumps/11Mar-emergency-run1/11032022_1419/dump_download_list.txt

**Test Scenario and results**
Branch: feat-fast-sync
Commit: 4081590dbdf7b9a262b49ee48f9b44c9a63bcad4
Network: 5 Validator + 2 Non-Validator
Test: Emergency Restart

- stop 2 of 5 initial validator nodes (set A) and stall network

- generate new validator list global state toml with 3 initial validators (set B) + 2 non-validators (set C)

- generate new emergency upgrade package + global state toml +  publish to all nodes of network

- restart the new validator list (set B + set C) nodes

- emergency restart successful with new validators = Set B + Set C

**Problem** - Once the network is up and running after an emergency restart. I start the initial 2 validators (set A)

- the Set A nodes have the upgrade and global state

- Set A nodes startup and start to sync

- Set A nodes sync to tip to participation mode successfully

- ISSUE:

the Set B nodes (3 validator node) get ejected, ie auction state info shows "inactive": true
only Set C nodes (non-validator nodes) are showing as active validators for current era and future era
the network continue to create new blocks

### PR DESCRIPTION
**Pull request by fizyk20**
Closes #2736 .

The root cause of the issue was this:
- The global state update was changing the validators by removing set A and adding set C.
- Nodes from set A and B gathered some rewards from previous eras and their stakes were quite high. Nodes from set C were added with small stakes.
- `global-state-update-gen` looks for bids made before the upgrade that are higher than the minimum stake among the new validators and removes them. This is to prevent other nodes from replacing the newly appointed validators right after the first era.
- In this case, since the nodes from set C had low stakes, this found bids from sets A and B and removed them. So nodes from set B were still validators, but were no longer bidding for being ones.
- After one era has passed, since nodes B weren't bidding, they were removed from the validator set, leaving only set C.

This PR changes the logic so that bids from nodes that keep being validators after the upgrade won't be removed.

### CODE REVIEW

File: utils/global-state-update-gen/src/auction_utils.rs [hunk 1]
```diff
@@ -64,18 +64,18 @@ pub fn find_large_bids(
...
         .values()
         .map(SeigniorageRecipient::stake)
         .min()
         .unwrap();
     builder
         .get_bids()
         .into_iter()
-        .filter(|(_pkey, bid)| bid.staked_amount() >= min_bid)
+        .filter(|(pkey, bid)| {
+            bid.staked_amount() >= min_bid && !seigniorage_recipients.contains_key(pkey)
```
Comment (goral09) [inline utils/global-state-update-gen/src/auction_utils.rs:77]: Isn't this a fairly arbitrary rule? Why not simply remove them and require being explicit about who is supposed to remain being a validator?

Comment (fizyk20) [reply utils/global-state-update-gen/src/auction_utils.rs:77]: There is also a part of the state that explicitly states who is going to be a validator - but that part is being overwritten by the auction contract at the end of each era based on the bids. So we need to change the bids in order for the auction contract to keep working as intended.

This is basically hacking the auction contract state so that it does what we want it to do.

Comment (goral09) [reply utils/global-state-update-gen/src/auction_utils.rs:77]: Shouldn't we change the bids of whoever is not the new validator to 0? Or remove them entirely.

**Review by afck — APPROVED** [review]
I agree this should address the issue.

But I wonder whether it would be better to separate the explicit validator set for right after the restart from the evictions, and make those explicit, too, instead of computing them this way.

File: utils/global-state-update-gen/src/auction_utils.rs (hunk 1 above)
Comment (fizyk20) [reply utils/global-state-update-gen/src/auction_utils.rs:77]: I guess we could, but this was intended to do the bare minimum necessary, which is to reset the bids of only the non-validators who would become validators when the auction is run. The smaller bids don't affect the validator set, and so it's not necessary to change them.

**Review by goral09 — APPROVED** [review]

**Comment by fizyk20** [comment]
@afck Hmm, I'm not sure what you mean. Could you elaborate?

This is not just about the evictions, BTW. This is also intended to handle non-validators that have bid before, but too low to get a slot, but would now become validators instead of the ones we appointed, because that was still more than the stakes of the new validators.

**Comment by afck** [comment]
What happens to their bids, i.e. to their actual money? Does it get evicted or automatically withdrawn?

I just think that either way it might be safer and more transparent to make the list of those validators explicit, too.

**Comment by fizyk20** [comment]
So what the tool does is it overwrites the bids with empty ones, but I'm not sure what that means for the actual money. @mpapierski could you help?

**Comment by mpapierski** [comment]
> So what the tool does is it overwrites the bids with empty ones, but I'm not sure what that means for the actual money. @mpapierski could you help?

If the tool overwrites a bid with an empty one, then the previous bid's amount should get moved back to the validator IMO. Otherwise total supply might be inaccurate

**Comment by fizyk20** [comment]
By "should get moved" do you mean that this should be already happening automatically, or that the tool should be doing that?
Also, in the ideal case, the only validators that have their bids removed will be the ones whose misbehavior caused enough trouble for the network to require an emergency upgrade, so just returning their funds to them seems to me like a bad idea.

**Comment by afck** [comment]
Ah, I see! Then I agree with @mpapierski:
_If_ we slash them, we should probably do that explicitly, too, and e.g. also reduce the amount of tokens in the auction contract accordingly.
If we don't want to slash them I think we should evict them, just like we automatically do for other faults. Returning their tokens for free seems too convenient in that case.

**Comment by fizyk20** [comment]
bors merge

**Comment by fizyk20** [comment]
We'll fix the outstanding issues in a future PR.
