### PR TITLE
GH-2604: Fix AssemblyScript ordering bug

### LINKED ISSUE #2604: Fix ordering in assemblyscript types
It should say bytes[i] instead of bytes[0]
https://github.com/casper-network/casper-node/blob/14175aebff6219fe09fb2b77ac6c141a2f81b757/smart_contracts/contract_as/assembly/key.ts#L47-L55

### PR DESCRIPTION
**Pull request by mpapierski**
Closes #2604

Fixes a bug where account hashes were not properly ordered.

### CODE REVIEW

File: smart_contracts/contract_as/assembly/key.ts [hunk 1]
```diff
@@ -47,19 +47,25 @@ export class AccountHash {
     @operator(">")
     graterThan(other: AccountHash): bool {
```
Comment (goral09) [inline smart_contracts/contract_as/assembly/key.ts]: BTW, this should be _greater_ :)

**Review by goral09 — APPROVED** [review]

File: smart_contracts/contract_as/assembly/key.ts (hunk 1 above)
Comment (mpapierski) [reply smart_contracts/contract_as/assembly/key.ts]: Fixed
