### PR TITLE
Make get_package handle `Key::Hash`

### LINKED ISSUE #5050: [BUG] Error when calling a contract using contract package hash
Bug reported by David Hernando from MAKE

Bug Description:

The reportee's question and error he faced;

> With AddressableEntities off, is it possible to call a contract by its contract package hash? I get an error with rc5:
> ```
> Error in request. [Code: -32016] Invalid transaction.
> Data: "the transaction was invalid: no such package at hash"
> ```

This is how the transaction was built;
```
            "entry_point": {
              "Custom": "unstake"
            },
            "target": {
              "Stored": {
                "id": {
                  "ByPackageHash": {
                    "addr": "601d407c7f1e339f4afd8ab6fcc4edc53619b3986c1ae84a6b3791b2ae394f8c",
                    "version": null
                  }
                },
                "runtime": "VmCasperV1"
              }
            }
```
The user faced a similar error with `account_put_deploy`, however, according to him, calling the contract by package name works normally.

The user also reported;

> I'm using an SDK, but also tried with `casper-client` to send the transaction.
> This is when I realized the node may be expecting a Package, because casper client only accepts a `package-0123...def` style key.
> 

```
casper-client put-transaction package -v -k /home/casper/casper-nctl/assets/net-1/users/user-1/secret_key.pem \
    -n http://127.0.0.1:11101/rpc \
    --package-address package-9761df244f22aa4538cc844d29892086330e37cf157b213a8991d648fde34b48 \
    --session-entry-point unstake \
    --pricing-mode classic \
    --standard-payment true \
    --chain-name casper-net-1 \
    -p 5000000000 \
    -g 1
```

### PR DESCRIPTION
**Pull request by darthsiroftardis**
CHANGELOG:

- Amend `get_package` on the effect builder to take a package addr and handle retrieving both contract packages and packages.

Closes #5050

### CODE REVIEW

File: node/src/components/transaction_acceptor/tests.rs [hunk 1]
```diff
@@ -2357,6 +2360,7 @@ async fn should_reject_transaction_v1_with_missing_version_in_session_contract_p
         ContractPackageScenario::MissingContractVersion,
     );
     let result = run_transaction_acceptor(test_scenario).await;
+    println!("{:?}", result);
```
Comment (EdHastingsCasperAssociation) [inline node/src/components/transaction_acceptor/tests.rs]: :dagger:

File: node/src/effect.rs [hunk 2]
```diff
@@ -2001,16 +2001,35 @@ impl<REv> EffectBuilder<REv> {
...
-        if let QueryResult::Success { value, .. } = self.query_global_state(query_request).await {
-            value.into_package().map(Box::new)
-        } else {
-            None
+        match self.query_global_state(query_request).await {
+            QueryResult::RootNotFound | QueryResult::Failure(_) => None,
+            QueryResult::ValueNotFound(_) => {
+                let query_request =
+                    QueryRequest::new(state_root_hash, Key::SmartContract(package_addr), vec![]);
+                error!("requesting under different key");
```
Comment (EdHastingsCasperAssociation) [inline node/src/effect.rs]: this isn't really an error...if we need to log this debug seems like a better fit

File: node/src/components/transaction_acceptor/tests.rs (hunk 1 above)
Comment (darthsiroftardis) [reply node/src/components/transaction_acceptor/tests.rs]: I thought I HAD

File: node/src/effect.rs (hunk 2 above)
Comment (darthsiroftardis) [reply node/src/effect.rs]: Will do!

Comment (darthsiroftardis) [reply node/src/effect.rs]: I think I added it when the tests were failing must've forgotten to remove it, I think debug makes sense

**Review by EdHastingsCasperAssociation — APPROVED** [review]
Approved assuming comments are addressed
