### PR TITLE
nctl/nightly tests: fix upgrade scenario 9

### LINKED ISSUE #3620: Upgrade 9 test failing

### PR DESCRIPTION
**Pull request by alsrdn**
We allow a node of the same binary to sync to a trusted hash of an older protocol version only if the trusted hash is within the allowed sync leap range. Adjust the test to check that if the trusted hash is not within the allowed range we don't allow the new node to sync.

Fixes: https://github.com/casper-network/casper-node/issues/3620

### CODE REVIEW

File: utils/nctl/sh/scenarios-upgrades/upgrade_scenario_09.sh [hunk 1]
```diff
@@ -56,8 +56,14 @@ function _main()
     POST_UPGRADE_BLOCK_HASH="$($(get_path_to_client) get-block --node-address "$(get_node_address_rpc '2')" | jq -r '.result.block.hash')"
 
     _step_05
-    _step_06
-    _step_07 "$STAGE_ID" "$ACTIVATION_POINT" "$PRE_UPGRADE_BLOCK_HASH" "$POST_UPGRADE_BLOCK_HASH"
+    # step 6 - start node 6 with trusted hash withing the allowed range
+    log_step_upgrades 6 "awaiting 1 eras to start node 6"
```
Comment (Fraser999) [inline utils/nctl/sh/scenarios-upgrades/upgrade_scenario_09.sh]:
```suggestion
    # step 6 - start node 6 with trusted hash within the allowed range
    log_step_upgrades 6 "awaiting 1 era to start node 6"
```

**Review by Fraser999 — APPROVED** [review]
Couple of nitpicks, but LGTM otherwise.

File: utils/nctl/sh/scenarios-upgrades/upgrade_scenario_09.sh (hunk 1 above)
Comment (alsrdn) [reply utils/nctl/sh/scenarios-upgrades/upgrade_scenario_09.sh]: Fixed in https://github.com/casper-network/casper-node/pull/3644/commits/658b5260dd58ab458deb8a60910b7ed0c64a56b6

**Review by Fraser999 — APPROVED** [review]

File: utils/nctl/sh/scenarios-upgrades/upgrade_scenario_09.sh [hunk 2]
```diff
@@ -163,46 +169,33 @@ function _step_05()
     done
 }
 
-# Step 06: Await 1 era.
-function _step_06()
```
Comment (TomVasile) [inline utils/nctl/sh/scenarios-upgrades/upgrade_scenario_09.sh:167]: Was there a reason to change the convention that the test is using?

**Review by TomVasile — CHANGES_REQUESTED** [review]
Blocking for now.  Running the test locally, I'm seeing node 6 die still. Will discuss in standup.

**Comment by alsrdn** [comment]
> Blocking for now. Running the test locally, I'm seeing node 6 die still. Will discuss in standup.

Node 6 was failing due to the issue fixed by this PR: https://github.com/casper-network/casper-node/pull/3639
I've merged back `dev` into this branch and it should pass now.

File: utils/nctl/sh/scenarios-upgrades/upgrade_scenario_09.sh (hunk 2 above)
Comment (alsrdn) [reply utils/nctl/sh/scenarios-upgrades/upgrade_scenario_09.sh:167]: Initially I saw no point in having them as separate functions, but it makes sense for convention. Added the step functions back in https://github.com/casper-network/casper-node/pull/3644/commits/e8c82e43f80f8f865ed042d1b0d044761a9651be

File: utils/nctl/sh/scenarios-upgrades/upgrade_scenario_09.sh [hunk 3]
```diff
@@ -163,46 +163,51 @@ function _step_05()
     done
 }
 
-# Step 06: Await 1 era.
+# Step 06: Await 1 era and then start node 6 with trusted hash within the allowed range
```
Comment (TomVasile) [inline utils/nctl/sh/scenarios-upgrades/upgrade_scenario_09.sh]: I'm wondering if we should also add a node here that starts up with the pre-upgrade hash? Since it would be allowed in the range, we should probably verify that as well.

File: utils/nctl/sh/scenarios-upgrades/upgrade_scenario_09.sh [hunk 4]
```diff
@@ -163,46 +163,51 @@ function _step_05()
...
-    log_step_upgrades 6 "awaiting next era"
-    nctl-await-n-eras offset='1' sleep_interval='5.0' timeout='180' node_id='2'
+    POST_UPGRADE_BLOCK_HASH=${1}
+    log_step_upgrades 6 "awaiting 1 era to start node 6"
+    nctl-await-n-eras offset='1' sleep_interval='5.0' timeout='300' node_id='2'
+    _stage_node_with_trusted_hash "6" "$STAGE_ID" "$ACTIVATION_POINT" "$POST_UPGRADE_BLOCK_HASH" 6
 }
 
-# Step 07: Stage node 6 with post-upgrade trusted hash and node 7 with pre-upgrade trusted hash
+# Step 07: Await 5 eras and then start node 7 with a trusted hash that is too old
```
Comment (TomVasile) [inline utils/nctl/sh/scenarios-upgrades/upgrade_scenario_09.sh]: Similar to my other comment, would a node started with the post-upgrade hash that was out of the range fail here? If so we should cover that too.

File: utils/nctl/sh/scenarios-upgrades/upgrade_scenario_09.sh [hunk 5]
```diff
@@ -163,46 +163,51 @@ function _step_05()
...
 function _step_07()
 {
-    local STAGE_ID=${1}
-    local ACTIVATION_POINT=${2}
-    local PRE_UPGRADE_BLOCK_HASH=${3}
-    local POST_UPGRADE_BLOCK_HASH=${4}
+    PRE_UPGRADE_BLOCK_HASH=${1}
```
Comment (TomVasile) [inline utils/nctl/sh/scenarios-upgrades/upgrade_scenario_09.sh]:
```suggestion
    local PRE_UPGRADE_BLOCK_HASH=${1}
```

File: utils/nctl/sh/scenarios-upgrades/upgrade_scenario_09.sh [hunk 6]
```diff
@@ -163,46 +163,51 @@ function _step_05()
     done
 }
 
-# Step 06: Await 1 era.
+# Step 06: Await 1 era and then start node 6 with trusted hash within the allowed range
 function _step_06()
 {
-    log_step_upgrades 6 "awaiting next era"
-    nctl-await-n-eras offset='1' sleep_interval='5.0' timeout='180' node_id='2'
+    POST_UPGRADE_BLOCK_HASH=${1}
```
Comment (TomVasile) [inline utils/nctl/sh/scenarios-upgrades/upgrade_scenario_09.sh]:
```suggestion
    local POST_UPGRADE_BLOCK_HASH=${1}
```

**Review by TomVasile — APPROVED** [review]
Ran locally and the test works as is! Just left some comments I think we might want to cover. Approving tentatively.

cc/ @Fraser999

File: utils/nctl/sh/scenarios-upgrades/upgrade_scenario_09.sh (hunk 3 above)
Comment (alsrdn) [reply utils/nctl/sh/scenarios-upgrades/upgrade_scenario_09.sh]: It shouldn't matter if the block is pre or post upgrade if the upgrade was successful. The condition for it to work is to provide a trusted block hash within the allowed range. Actually this is the reason why the test was failing in the past; node 7 was using a hash that was within the allowed range and didn't fail as expected.
So we can start 2 more nodes that have their hash within the allowed range, one pre and one post upgrade to see if it works but not sure it is necessary.

File: utils/nctl/sh/scenarios-upgrades/upgrade_scenario_09.sh (hunk 6 above)
Comment (alsrdn) [reply utils/nctl/sh/scenarios-upgrades/upgrade_scenario_09.sh]: added in https://github.com/casper-network/casper-node/pull/3644/commits/7f5aecd791c8b22d3cbd70ade3327c49ff75f862

File: utils/nctl/sh/scenarios-upgrades/upgrade_scenario_09.sh (hunk 5 above)
Comment (alsrdn) [reply utils/nctl/sh/scenarios-upgrades/upgrade_scenario_09.sh]: added in https://github.com/casper-network/casper-node/pull/3644/commits/7f5aecd791c8b22d3cbd70ade3327c49ff75f862

**Comment by alsrdn** [comment]
bors merge
