### PR TITLE
Fix run_equivocator_network test.

### LINKED ISSUE #1859: Non-det failure of `run_equivocator_network` test.
https://drone-auto-casper-network.casperlabs.io/casper-network/casper-node/1453/3/3 failed with

```
failures:

---- reactor::participating::tests::run_equivocator_network stdout ----
thread 'reactor::participating::tests::run_equivocator_network' panicked at 'assertion failed: `(left == right)`
  left: `[]`,
 right: `[PublicKey::Ed25519(5bc5542a73a3fd4e53c2f3c84838156cf8ce5de0db828a5644b1c6d883056aa6)]`', node/src/reactor/participating/tests.rs:319:13
```

source:
https://github.com/casper-network/casper-node/blob/dev/node/src/reactor/participating/tests.rs#L319

4.11.23 can we create equivocation through the diagnostic port?  Goal: make this deterministic and then address.   Use the equivocation mechanism available in Zug

### PR DESCRIPTION
**Pull request by afck**
Delay only _consensus_ messages in the test, not other network requests.

The test was flaky before, and I suspect it had to do with the fact that we were delaying all outgoing messages from Alice's doppelgänger node, instead of just the consensus messages. I verified that this was also delaying address gossiper messages, so it might have interfered with establishing connections. It's hard to be sure, though, because the failures occurred only once every few days, and only on CI.

With this change, all incoming and outgoing consensus messages get delayed for three rounds, and the timer starts with the first incoming or outgoing consensus message.

The delay itself is meant to guarantee that Alice's two nodes will in fact produce an equivocation: If they don't hear from each other for more than one round, they will both produce a Highway unit.

Closes #1859.

### CODE REVIEW

**Comment by fizyk20** [comment]
Could you add a short comment explaining why delaying just the consensus messages should fix the test? I think I understand why delaying them is useful (because we delay consensus detecting a doppelgänger until some equivocating messages have been produced, right?), but I'm not sure why other messages being delayed as well would be breaking it again.

File: node/src/reactor/participating/tests.rs [hunk 1]
```diff
@@ -332,18 +337,19 @@ async fn run_equivocator_network() {
...
-                    | ParticipatingEvent::Consensus(consensus::Event::MessageReceived { .. }),
-                    Some(first_message_time),
-                ) => first_message_time,
-                (ParticipatingEvent::Consensus(consensus::Event::MessageReceived { .. }), None) => {
-                    maybe_first_message_time = Some(now);
-                    now
-                }
+            match &event {
+                ParticipatingEvent::NetworkAnnouncement(NetworkAnnouncement::MessageReceived {
+                    payload,
```
Comment (xcthulhu) [inline node/src/reactor/participating/tests.rs:342]: So if you put `deref payload` here, could you combine this branch and the branch below?

File: node/src/reactor/participating/tests.rs [hunk 2]
```diff
@@ -332,18 +337,19 @@ async fn run_equivocator_network() {
...
+                    ..
+                }) if matches!(*payload, Message::Consensus(_)) => {}
+                ParticipatingEvent::NetworkRequest(
+                    NetworkRequest::SendMessage { payload, .. }
+                    | NetworkRequest::Broadcast { payload, .. }
+                    | NetworkRequest::Gossip { payload, .. },
+                ) if matches!(**payload, Message::Consensus(_)) => {}
                 _ => return Either::Right(event),
             };
+            let first_message_time = *maybe_first_message_time.get_or_insert(now);
```
Comment (xcthulhu) [inline node/src/reactor/participating/tests.rs:352]: Might as well inline `now` here.

File: node/src/reactor/participating/tests.rs (hunk 1 above)
Comment (afck) [reply node/src/reactor/participating/tests.rs:342]: No, because this `payload` is of type `&P` and the other ones are `&Box<P>`. And box patterns are still feature gated and not available in stable rust.

File: node/src/reactor/participating/tests.rs (hunk 2 above)
Comment (afck) [reply node/src/reactor/participating/tests.rs:352]: I'm also using it in the next line.

**Review by goral09 — APPROVED** [review]

**Review by fizyk20 — APPROVED** [review]
Thanks for the updated description :+1:

**Comment by afck** [comment]
bors merge
