### PR TITLE
Add SSE server tests and fix issues exposed by these

### LINKED ISSUE #1525: Add tests for SSE server

### PR DESCRIPTION
**Pull request by Fraser999**
This PR adds a comprehensive test suite for the SSE server.  In doing so, it revealed two issues in the server, both of which are fixed in this PR:
* The server did not handle malformed queries well.  In some cases it ignored them and in others it treated them as a bad path
* The server did not handle the `start_from` query properly in the case where the buffered events' IDs wrapped past `u32::MAX` back to `0`

The PR also introduces a test which checks the generated JSON schema for the `SseData` enum against a previously-generated, hard-coded schema (added to "resources/test").  Rather than being particularly useful as a unit test, it will instead make it somewhat simple to view differences between discrete versions of the data produced by the SSE server.

Closes #1525.

### CODE REVIEW

**Review by nilz3ro — APPROVED** [review]
I think these changes look good, but I would like another person to review them since I'm not familiar with these components.

File: node/src/components/event_stream_server/tests.rs [hunk 1]
```diff
@@ -0,0 +1,899 @@
...
+const BUFFER_LENGTH: u32 = EVENT_COUNT / 2;
+/// The maximum amount of time to wait for a test server to complete.  If this time is exceeded, the
+/// test has probably hung, and should be deemed to have failed.
+const MAX_TEST_TIME: Duration = Duration::from_secs(1);
+/// The duration of the sleep called between each event being sent by the server.
+const DELAY_BETWEEN_EVENTS: Duration = Duration::from_millis(1);
+
+thread_local!(
+    /// A per-test identifier for the clients.
+    static CLIENT_ID: RefCell<usize> = RefCell::new(0)
```
Comment (marc-casperlabs) [inline node/src/components/event_stream_server/tests.rs:45]: Is it possibly sufficient to use a random `u64` instead and not deal with any thread local stuff?

File: node/src/components/event_stream_server/tests.rs [hunk 2]
```diff
@@ -0,0 +1,899 @@
...
+    protocol_version: ProtocolVersion,
+    events: Vec<SseData>,
+    first_event_id: Id,
+    server_join_handle: Option<JoinHandle<()>>,
+    server_stopper: ServerStopper,
+}
+
+impl TestFixture {
+    /// Constructs a new `TestFixture` including `EVENT_COUNT` random events ready to be served.
+    fn new(rng: &mut TestRng) -> Self {
```
Comment (marc-casperlabs) [inline node/src/components/event_stream_server/tests.rs:175]: Maybe pass in `EVENT_COUNT` here, since we might want to use different settings for different tests?

File: node/src/components/event_stream_server/tests.rs [hunk 3]
```diff
@@ -0,0 +1,899 @@
...
+            first_event_id: 0,
+            server_join_handle: None,
+            server_stopper: ServerStopper::new(),
+        }
+    }
+
+    /// Creates a new `EventStreamServer` and runs it in a tokio task, returning the actual address
+    /// the server is listening on.
+    ///
+    /// Only one server can be run at a time; this panics if there is already a server task running.
```
Comment (marc-casperlabs) [inline node/src/components/event_stream_server/tests.rs:205]: Are we limiting ourselves to one instance (and thus one test in parallel) due to port collision issues?

File: node/src/components/event_stream_server/tests.rs [hunk 4]
```diff
@@ -0,0 +1,899 @@
...
+    //   * data:<JSON-encoded ApiVersion> (note, no ID line follows this first event)
+    // then the following three repeated for as many events as are applicable to that stream:
+    //   * data:<JSON-encoded event>
+    //   * id:<integer>
+    //   * empty line
+    // then finally, repeated keepalive lines until the server is shut down.
+    let mut received_events = Vec::new();
+    let mut line_itr = response_text.lines();
+    while let Some(data_line) = line_itr.next() {
+        let data = match data_line.strip_prefix("data:") {
```
Comment (marc-casperlabs) [inline node/src/components/event_stream_server/tests.rs:419]: Maybe I've written a few too many parsers in my recent time, but how about adding a function

`fn parse_line<T: FromStr>(expected_key: &str, value: T) -> Result<T, ParseError>` (or a custom trait instead of `FromStr`)

and then writing this more readable as something roughly along the lines of 

```
let data: ApiVersion = parse_line("data", line_itr.next().ok_or(ParseError::ExpectedLine)?)?;
let data: Event = parse_line("data, line_itr.next().ok_or(ParseError::ExpectedLine)?)?;
let data: i64 = parse_line("id, line_itr.next().ok_or(ParseError::ExpectedLine)?)?;
// ...
```

**Review by marc-casperlabs — APPROVED** [review]
Some suggestions, but if none were addressed, I'd still be fine merging this :)

File: node/src/components/event_stream_server/tests.rs (hunk 1 above)
Comment (Fraser999) [reply node/src/components/event_stream_server/tests.rs:45]: Passing the RNG in here is painful, as in some tests this is called in parallel and the borrow checker has thoughts about that.  I'll pass a `&str` so we can keep with the current approach of having the clients named sequentially to make the log output in the tests more understandable.

File: node/src/components/event_stream_server/tests.rs (hunk 2 above)
Comment (Fraser999) [reply node/src/components/event_stream_server/tests.rs:175]: None of the tests need this flexibility, so I'd rather avoid adding an extra parameter.  We can always do it later if we add new tests which might need that.

File: node/src/components/event_stream_server/tests.rs (hunk 3 above)
Comment (Fraser999) [reply node/src/components/event_stream_server/tests.rs:205]: No, purely for simplicity in the tests.  The separate unit tests all run in parallel, but I couldn't see a use for running two servers in parallel in a single test.

File: node/src/components/event_stream_server/tests.rs (hunk 4 above)
Comment (Fraser999) [reply node/src/components/event_stream_server/tests.rs:419]: Hmm - that seems overly complex for what we need here.  While it would simplify the call site a little, it wouldn't be as simple as you show.  For example, parsing the data line is as simple as stripping the prefix `data:`.  However, we also handle the case where the expected data line is empty or is a keepalive.

I'll move the parsing wholesale to a new function as you suggest in the comment above to see if that helps a little.

Comment (Fraser999) [reply node/src/components/event_stream_server/tests.rs:419]: Hmm - that seems overly complex for what we need here.  While it would simplify the call site a little, it wouldn't be as simple as you show.  For example, parsing the data line is as simple as stripping the prefix `data:`.  However, we also handle the case where the expected data line is empty or is a keepalive.

I'll move the parsing wholesale to a new function as you suggest in the comment above to see if that helps a little.

**Comment by Fraser999** [comment]
bors merge

File: node/src/components/event_stream_server/tests.rs (hunk 4 above)
Comment (marc-casperlabs) [reply node/src/components/event_stream_server/tests.rs:414]: Sounds good to me. In the end, we probably want to have a proper SSE parser and not some quick inline solution I guess though.

File: node/src/components/event_stream_server/tests.rs (hunk 3 above)
Comment (marc-casperlabs) [reply node/src/components/event_stream_server/tests.rs:199]: Well, it's just tests, so I am fine with that :)
