### PR TITLE
Make run_equivocator_network test simpler and less flaky.

### LINKED ISSUE #1859: Non-det failure of `run_equivocator_network` test.
https://drone-auto-casper-network.casperlabs.io/casper-network/casper-node/1453/3/3 failed with

```
failures:

---- reactor::participating::tests::run_equivocator_network stdout ----
thread 'reactor::participating::tests::run_equivocator_network' panicked at 'assertion failed: `(left == right)`
  left: `[]`,
 right: `[PublicKey::Ed25519(5bc5542a73a3fd4e53c2f3c84838156cf8ce5de0db828a5644b1c6d883056aa6)]`', node/src/reactor/participating/tests.rs:319:13
```

source:
https://github.com/casper-network/casper-node/blob/dev/node/src/reactor/participating/tests.rs#L319

4.11.23 can we create equivocation through the diagnostic port?  Goal: make this deterministic and then address.   Use the equivocation mechanism available in Zug

### PR DESCRIPTION
**Pull request by afck**
This wraps the `Participating` reactor in a `FilterReactor` in the test, and delays the first few messages to and from one of the two nodes with the same key. That way, the nodes won't notice each other and will always equivocate in the first era.

Closes #1859

### CODE REVIEW

**Review by goral09 — COMMENTED** [review]
The test now looks quite nice. I wonder, if we can write a unit test now that asserts when the bid can be re-activated, what's the delay for that, that activating bid while you're evicted is a noop, etc.

**Review by fizyk20 — APPROVED** [review]
LGTM :+1: And nice one with the `FilterReactor` :slightly_smiling_face:

**Comment by afck** [comment]
> I wonder, if we can write a unit test now that asserts when the bid can be re-activated, what's the delay for that, that activating bid while you're evicted is a noop, etc.

Makes sense, but let's make that a separate ticket.

**Comment by afck** [comment]
I created #1922 for extending the test.

File: node/src/reactor/participating/tests.rs [hunk 1]
```diff
@@ -240,110 +259,100 @@ async fn run_equivocator_network() {
...
+                next_era_validators.push(
+                    header
+                        .next_era_validator_weights()
+                        .expect("validators")
+                        .clone(),
+                );
                 switch_blocks.push(header);
             }
         }
+    }
```
Comment (goral09) [inline node/src/reactor/participating/tests.rs]: This piece could be a separate method returning new data structure(s).

**Review by goral09 — APPROVED** [review]

File: node/src/reactor/participating/tests.rs [hunk 2]
```diff
@@ -240,110 +259,100 @@ async fn run_equivocator_network() {
...
+    let min_round_len = chain.chainspec.highway_config.min_round_length();
+    net.reactors_mut()
+        .find(|reactor| *reactor.inner().consensus().public_key() == alice_pk)
+        .unwrap()
+        .set_filter(move |event| match event {
+            ParticipatingEvent::NetworkRequest(_)
+            | ParticipatingEvent::Consensus(consensus::Event::MessageReceived { .. })
+                if Timestamp::now() < genesis_time + min_round_len * 2 =>
+            {
+                Either::Left(time::sleep(min_round_len.into()).event(move |_| event))
```
Comment (xcthulhu) [inline node/src/reactor/participating/tests.rs:332]: Looks like this is where we introduce the delay...

**Review by xcthulhu — APPROVED** [review]
LGTM

**Comment by afck** [comment]
bors merge
