### PR TITLE
Fix historical sync not announcing a meta block

### LINKED ISSUE #3863: Investigate if (and why?) DeployBuffer is not informed about historical blocks
DeployBuffer needs to be aware of deploys stored in historical blocks in order not to propose them again. This seems to be not happening, because we've been observing nodes that had the DeployBuffer::chain_index struct filled with only the forward blocks. We should confirm that the notification about historical blocks is indeed not happening, and if confirmed, fix it.

(potential fix should be easy, but creating a test may require some work)

### PR DESCRIPTION
**Pull request by georgepisaltu**
Fixes #3863 

This PR fixes a bug in which a block in the historical builder would not get announced as a meta block after it was marked complete, therefore, among other things, not notifying the deploy buffer of its existence. This was because the `maybe_block` method on the builder regressed after the latest changes which added extra state to `BlockAcquisitionState`, specifically `HaveFinalizedBlock` and `Complete`. These new states did not hold the block specifically (even though they had access to it at the time of the transition) and the `maybe_block` method would return `None`. As `maybe_block` is used to announce the meta block after marking it complete, no announcement would be made.

This PR fixes this by keeping the block around instead of discarding it and also adds a regression test for this scenario.

### CODE REVIEW

File: node/src/components/block_synchronizer/block_builder/tests.rs [hunk 1]
```diff
@@ -254,7 +254,7 @@ fn register_block_execution() {
     // execution.
     let finalized_block = Box::new(FinalizedBlock::from(block.clone()));
     builder.acquisition_state = BlockAcquisitionState::HaveFinalizedBlock(
-        *block.hash(),
+        Box::new(block),
```
Comment (rafal-ch) [inline node/src/components/block_synchronizer/block_builder/tests.rs:256]: I know it's not a part of this PR, but can you update the comment, which still says about `HaveAllDeploys`.
Actually, my preference would be to remove the comment, if you don't mind :)

File: node/src/components/block_synchronizer/block_acquisition.rs [hunk 2]
```diff
@@ -108,8 +108,8 @@ pub(super) enum BlockAcquisitionState {
     HaveApprovalsHashes(Box<Block>, SignatureAcquisition, DeployAcquisition),
     HaveAllDeploys(Box<Block>, SignatureAcquisition),
     HaveStrictFinalitySignatures(Box<Block>, SignatureAcquisition),
-    HaveFinalizedBlock(BlockHash, Box<FinalizedBlock>, Vec<Deploy>, bool),
-    Complete(BlockHash, u64),
+    HaveFinalizedBlock(Box<Block>, Box<FinalizedBlock>, Vec<Deploy>, bool),
```
Comment (rafal-ch) [inline node/src/components/block_synchronizer/block_acquisition.rs:121]: I have a question here: is `HaveFinalizedBlock` involved in the historical flow? My understanding was that for historical blocks, we go directly from `HaveStrictFinalitySignatures` to `Complete`. The confusion comes from the fact that we're fixing the historical sync with this PR.

So, is this `Box<Block>` only needed to carry on the information about block when we're constructing `Complete` in the forward flow?

Also, this is now super-confusing to have both `Block` and `FinalizedBlock` alongside each other, indicating that the overall design of the block acquisition could use some improvement in the future.

For now, can we at least add a comment of what these two mean in the context of `HaveFinalizedBlock`?

**Review by rafal-ch — APPROVED** [review]
LGTM :+1: 

With minor nit and a suggestion to add some explanatory comment to `BlockAcquisitionState`.

File: node/src/components/block_synchronizer/block_acquisition.rs (hunk 2 above)
Comment (georgepisaltu) [reply node/src/components/block_synchronizer/block_acquisition.rs:121]: We need to keep the block around in `HaveFinalizedBlock` because we'll need it in `Complete` when we want to make the transition. Yes, `HaveFinalizedBlock` is used only in the forward flow, but it's necessary as `Complete` is the final state in both historical and forward sync.

I agree it's confusing to have both the `Block` and the `FinalizedBlock` in there, but in my mind it's not the worst. Some of the things in the state are necessary for the current step (like `FinalizedBlock`), others are needed for future states. It's unfortunate that we have both a `Block` and a `FinalizedBlock`, but we need both it seems. I agree with you though, a refactor would be welcome indeed.

I will add the comment in a later commit.

File: node/src/components/block_synchronizer/tests.rs [hunk 3]
```diff
@@ -1498,7 +1498,7 @@ async fn fwd_have_strict_finality_requests_enqueue_when_finalized_block_is_creat
         .expect("Forward builder should have been initialized");
     assert_matches!(
         fwd_builder.block_acquisition_state(),
-        BlockAcquisitionState::HaveFinalizedBlock(block_hash, _, _, _) if block_hash == block.hash()
+        BlockAcquisitionState::HaveFinalizedBlock(actual_block, _, _, _) if *actual_block.hash() == *block.hash()
```
Comment (fizyk20) [inline node/src/components/block_synchronizer/tests.rs:1501]: Nit: do we need to dereference both sides here?

File: node/src/components/block_synchronizer/tests.rs [hunk 4]
```diff
@@ -1569,7 +1569,7 @@ async fn fwd_builder_status_is_executing_when_block_is_enqueued_for_execution()
     fwd_builder.register_made_finalized_block(block.clone().into(), Vec::new());
     assert_matches!(
         fwd_builder.block_acquisition_state(),
-        BlockAcquisitionState::HaveFinalizedBlock(block_hash, _, _, _) if block_hash == block.hash()
+        BlockAcquisitionState::HaveFinalizedBlock(actual_block, _, _, _) if *actual_block.hash() == *block.hash()
```
Comment (fizyk20) [inline node/src/components/block_synchronizer/tests.rs:1572]: Nit: same as above.

File: node/src/components/block_synchronizer/block_builder/tests.rs (hunk 1 above)
Comment (georgepisaltu) [reply node/src/components/block_synchronizer/block_builder/tests.rs:256]: Done.

File: node/src/components/block_synchronizer/block_acquisition.rs (hunk 2 above)
Comment (georgepisaltu) [reply node/src/components/block_synchronizer/block_acquisition.rs:121]: Done.

**Review by fizyk20 — APPROVED** [review]

**Review by EdHastingsCasperAssociation — APPROVED** [review]
The state machine is too coarse

in historical flow it should go:

HaveStrictFinality -> need to mark complete -> HaveAnnouncedComplete -> need marked complete ->  Complete

in forward flow it should go: 

HaveStrictFinality -> need enque for executed -> HaveEnqueuedExecution -> need executed -> HaveExecuted -> need to mark complete -> HaveAnnouncedComplete -> need marked complete ->  Complete

Go ahead and merge this, and I'll circle back and unfurl the state machine to properly represent all the states

File: node/src/components/block_synchronizer/tests.rs (hunk 3 above)
Comment (georgepisaltu) [reply node/src/components/block_synchronizer/tests.rs:1501]: There is no particular reason other than I always deref values I'm comparing in tests out of habit. Same for below.

Comment (fizyk20) [reply node/src/components/block_synchronizer/tests.rs:1501]: There is a [blanket implementation](https://doc.rust-lang.org/std/cmp/trait.PartialEq.html#impl-PartialEq%3C%26B%3E-for-%26A) of `PartialEq` for references to types that are `PartialEq` themselves, so personally I prefer no dereffing in such situations, as it's superfluous - but as I said, just a nit, not particularly important :wink:
