### PR TITLE
Fix update of joining set

### LINKED ISSUE #3172: Fix incorrect update of the "joining set"
We should not update the joining set when we receive an incoming connection, because the message_sender which is handling the corresponding outgoing connection will not receive the update of the remote joiner state.
Such desync may cause the node to try to send requests that are not safe for joiners, to the joining node, because the outgoing connection may outlive the incoming connection, i.e. it may take some time to drop "our" outgoing connection after a peer has closed the corresponding incoming connection.
We should also bump the log level if we detect that a peer is trying to query a joiner from warn to error because with the changes introduced in this ticket we expect it to never happen. So when it does, we want to alert loudly.

### PR DESCRIPTION
**Pull request by rafal-ch**
This PR changes the following:
* the "joining peer set" is **not** updated upon establishing the incoming connection (such an update may cause the node to try to send requests that are not safe for joiners, to the joining node_)
* bumps the log message severity if we detect that a peer is trying to query a joiner from `warn` to `error`
* introduces the helper `HandshakeOutcome` struct

Closes https://github.com/casper-network/casper-node/issues/3172

### CODE REVIEW

File: node/src/components/small_network.rs [hunk 1]
```diff
@@ -510,7 +509,17 @@ where
...
+                    // We should not update the joining set when we receive an incoming connection,
+                    // because the `message_sender` which is handling the corresponding outgoing
+                    // connection will not receive the update of the remote joiner state.
+                    //
+                    // Such desync may cause the node to try to send requests that are not safe for
+                    // joiners, to the joining node, because the outgoing connection may outlive the
+                    // incoming connection, i.e. it may take some time to drop "our" outgoing
+                    // connection after a peer has closed the corresponding incoming connection.
+
+                    // self.update_joining_set(peer_id, is_joiner);
```
Comment (goral09) [inline node/src/components/small_network.rs]: Is this left commented out on purpose?

File: node/src/components/small_network/tasks.rs [hunk 2]
```diff
@@ -63,6 +63,13 @@ use crate::{
 /// successfully handed over to the kernel for sending.
 pub(super) type MessageQueueItem<P> = (Arc<Message<P>>, Option<AutoClosingResponder<()>>);
 
+struct HandshakeOutcome {
+    framed_transport: FramedTransport,
+    public_addr: SocketAddr,
+    peer_consensus_public_key: Option<PublicKey>,
+    is_joiner: bool,
```
Comment (goral09) [inline node/src/components/small_network/tasks.rs]:
```suggestion
    is_peer_joiner: bool,
```

I prefer this over `is_joiner` as the latter can be confused with a flag indicating whether _we_ are a joiner node.

**Review by goral09 — APPROVED** [review]

File: node/src/components/small_network.rs (hunk 1 above)
Comment (rafal-ch) [reply node/src/components/small_network.rs]: Yes, to make the way we attempted to fix the bug explicit. I see no problem removing it if you'd like to.

File: node/src/components/small_network/tasks.rs (hunk 2 above)
Comment (rafal-ch) [reply node/src/components/small_network/tasks.rs]: I agree.
Changed back to `is_peer_joiner` in 96d9555915bfc004396edba41cf9bc4d11a98061

File: node/src/components/small_network.rs (hunk 1 above)
Comment (marc-casperlabs) [reply node/src/components/small_network.rs]: I think our policy is to remove commented out code, so let's take it out!

File: node/src/components/small_network/tasks.rs [hunk 3]
```diff
@@ -63,6 +63,13 @@ use crate::{
 /// successfully handed over to the kernel for sending.
 pub(super) type MessageQueueItem<P> = (Arc<Message<P>>, Option<AutoClosingResponder<()>>);
 
+struct HandshakeOutcome {
```
Comment (marc-casperlabs) [inline node/src/components/small_network/tasks.rs:67]: Could you add docs on the struct and its members? :sparkles: I try to be diligent about this, even (or especially :)) internal structs.

File: node/src/components/small_network/tasks.rs [hunk 4]
```diff
@@ -134,11 +141,16 @@ where
...
 
     // Negotiate the handshake, concluding the incoming connection process.
-    match negotiate_handshake::<P, _>(&context, framed, connection_id).await {
-        Ok((framed, public_addr, peer_consensus_public_key, is_joiner)) => {
+    match negotiate_handshake::<P, _>(&context, framed_transport, connection_id).await {
+        Ok(HandshakeOutcome {
+            framed_transport,
+            public_addr,
+            peer_consensus_public_key,
+            is_peer_joiner: is_joiner,
```
Comment (marc-casperlabs) [inline node/src/components/small_network/tasks.rs:157]: We could do without the rename here, for clarity, I think. I know it keeps the diff smaller, but I'd be too tempted to remove the alias later on :)

**Review by marc-casperlabs — APPROVED** [review]
Only nitpicks which would be nice to fix. Otherwise looks good to me!

File: node/src/components/small_network/tasks.rs (hunk 4 above)
Comment (rafal-ch) [reply node/src/components/small_network/tasks.rs:157]: I'll leave it as is, because this field will probably be removed in https://github.com/casper-network/casper-node/pull/3179

File: node/src/components/small_network.rs (hunk 1 above)
Comment (rafal-ch) [reply node/src/components/small_network.rs]: Removed in fd62aa2c41eed5489c3576b82438fe5d964603f2

File: node/src/components/small_network/tasks.rs (hunk 3 above)
Comment (rafal-ch) [reply node/src/components/small_network/tasks.rs:67]: Comments added here: a50a50659bb71cc39d0bf6b1a284c968948ca4f6
