### PR TITLE
Fix storage tests

### LINKED ISSUE #3386: Fix storage and sync leap tests
all but one of the storage ones are related to sync leap

### PR DESCRIPTION
**Pull request by Fraser999**
This PR fixes or removes the remaining sync-leap and storage tests.

Closes #3386.

### CODE REVIEW

File: node/src/components/storage/tests.rs [hunk 1]
```diff
@@ -99,50 +100,37 @@ fn create_sync_leap_test_chain(
...
-                parent.map(|block| *block.hash()),
-                if *height == 0 || *height == 3 || *height == 6 || *height == 9 {
-                    trusted_validator_weights.clone()
-                } else {
-                    BTreeMap::new()
-                },
-            );
-
-            blocks.push(block);
+    let block_count = 13 + include_switch_block_at_tip as u64;
```
Comment (rafal-ch) [inline node/src/components/storage/tests.rs:103]: smells like C++ ;-)

**Review by rafal-ch — APPROVED** [review]
LGTM :+1:
