### PR TITLE
Fix issue when a node that is supposed to be a validator gets stuck if it comes back after an upgrade slightly later than the other validators

### LINKED ISSUE #3852: Revisit the MainReactor::switch_block_header field
This field was initially intended to be a cache of the most recent switch block (initially set to None, and once set to Some it should stay Some). At some point, we added code that sets it back to None, which is probably incorrect. We need to revisit this code, possibly removing the switch_block_header field and replacing it with a call to storage. This also requires checking if all places that rely on this field do so correctly

### LINKED ISSUE #3961: Fix issue where a node coming up for upgrade to 1.5.0 is sometimes hung
If a node that is supposed to be a validator lags a little bit behind when upgrading from 1.4.x to 1.5 it can happen that it gets stuck in validate because the immediate switch block was not executed and cannot be synced.

### PR DESCRIPTION
**Pull request by alsrdn**
This PR fixes an issue where a node that is supposed to be a validator gets stuck if it comes back after an upgrade slightly later than the other validators. There are 3 commits that fix this issue:
* Remove the usage of `switch_block_header` for determining if a node should commit upgrade and use the highest **complete** block header instead to do that determination:
  * The control logic was using the cached `switch_block_header` to determine if the node is ready to commit an upgrade. This field was not only updated with the header of the latest complete block and was set also by the `CatchUp` logic to the highest block header that the node has stored. In the case where a `SyncLeap` is received, the headers in that message are stored. This in turn can lead `switch_block_header` to hold a header of a block that may not have been marked as completed.
  * Because of this the control logic was tricked into thinking that it should not commit an upgrade (because there was a header that was of the newer protocol version received through SyncLeap) and switch to `KeepUp` and then to `Validate` (if it was supposed to be a validator) even if the node did not have the immediate switch block marked as complete.
  * This can happen if the node that is supposed to be validating comes up after an upgrade a little later than the other nodes in the network; in this case it comes late enough such that its peers already completed and are responding to a SyncLeap with the newly created immediate switch block.
* Preventing the reactor from looping indefinitely in the `Upgrading` state and moving it to `CatchUp` where it can try to recover:
  * In some cases, the node can become stuck trying to commit the upgrade due to different reasons. One scenario is that of a node that comes up a little later than the others after an emergency upgrade and tries to commit the upgrade. Because the other validators may have already finished gossiping the new immediate switch block, this node may not have heard the gossip since it was down. In this situation the node will not be able to store the immediate switch block it created since it can't hear about sufficient signatures from the other peers.
  * Instead of looping in the `Upgrading` state indefinitely without no chance of being able to store the block, if enough time has passed we switch the node back to `CatchUp`. In this state it can determine if it is at tip or not and either try to upgrade again or sync back the immediate switch block from the network.
* Relaxing the filtering out of switch blocks preceding an upgrade in a `SyncLeap` response when trying to determine the era validators from that message:
  * We can determine if an upgrade did change the validator set or not by looking at the chainspec. If the upgrade to the current protocol version did not alter the validator set, then we can use the validators in the switch block preceding the upgrade.

Fixes: https://github.com/casper-network/casper-node/issues/3961
Fixes: https://github.com/casper-network/casper-node/issues/3852

### CODE REVIEW

**Comment by alsrdn** [comment]
bors try

File: node/src/reactor/main_reactor/upgrading_instruction.rs [hunk 1]
```diff
@@ -1,5 +1,9 @@
 use std::time::Duration;
 
+use casper_types::{TimeDiff, Timestamp};
+
+const UPGRADE_TIMEOUT_SECONDS: u32 = 30;
```
Comment (georgepisaltu) [inline node/src/reactor/main_reactor/upgrading_instruction.rs]: We should probably move this to the config so that we can adjust this to specific validator setups easily.

File: node/src/reactor/main_reactor/control.rs [hunk 2]
```diff
@@ -471,16 +484,30 @@ impl MainReactor {
...
+            Ok(Some(highest_complete_block)) => {
+                if highest_complete_block.header().is_switch_block() {
+                    highest_complete_block.take_header()
+                } else {
+                    return false;
+                }
+            }
+            Ok(None) => {
+                return false;
+            }
```
Comment (fizyk20) [inline node/src/reactor/main_reactor/control.rs]:
```suggestion
            Ok(Some(highest_complete_block)) if highest_complete_block.header().is_switch_block( => {
                highest_complete_block.take_header()
            }
            Ok(Some(_)) | Ok(None) => {
                return false;
            }
```

File: node/src/types/sync_leap.rs [hunk 3]
```diff
@@ -148,11 +159,22 @@ impl SyncLeap {
...
                             .get(&(block_header.height() + 1))
                             .map_or(true, |other_protocol_version| {
-                                block_header.protocol_version() == *other_protocol_version
+                                if block_header.protocol_version() == *other_protocol_version {
+                                    true
+                                } else if *other_protocol_version == current_protocol_version {
+                                    !validators_changed_in_current_protocol
+                                } else {
+                                    false
+                                }
```
Comment (fizyk20) [inline node/src/types/sync_leap.rs:177]: As discussed on Slack, I don't really like this approach, but it should work and it seems that other approaches would be significantly more complex, so let's go with this one for now.

**Review by fizyk20 — APPROVED** [review]

File: node/src/reactor/main_reactor/upgrading_instruction.rs (hunk 1 above)
Comment (alsrdn) [reply node/src/reactor/main_reactor/upgrading_instruction.rs]: Added in https://github.com/casper-network/casper-node/pull/3971/commits/18bce1adea6345647e1568f2068b7ddc74c5ed1f

File: node/src/reactor/main_reactor/control.rs (hunk 2 above)
Comment (alsrdn) [reply node/src/reactor/main_reactor/control.rs]: Fixed in https://github.com/casper-network/casper-node/pull/3971/commits/18bce1adea6345647e1568f2068b7ddc74c5ed1f

File: node/src/types/sync_leap.rs (hunk 3 above)
Comment (alsrdn) [reply node/src/types/sync_leap.rs:177]: Yes, I have a POC of a different approach that does not require us to look at the chainspec here: https://github.com/casper-network/casper-node/commit/6076548d9170deb0fec6c5644f43525d05de0808

The issue with this approach is that the control logic becomes even more complicated; to make it work I had to re-introduce a behaviour in the block synchronizer where it has to wait for the era validators to be populated instead of fetching a sync leap. While it works in this particular scenario, there were other scenarios where this behaviour led to some issues which are hard to re-test in the current state, so we may resurrect some bugs that we had in the past.
The other big change to the control logic is checking the sync leaper status while syncing in the CatchUp control logic. While it would make sense to do this so that we can finalize all sync leap requests that are in flight it can also delay the poll of the accumulator if a leap is in progress.

I think we need to refactor the validator matrix (and the way we do updates to it) to have more of a transactional interface or change the code so it doesn't depend on the effect builder and we can await updates to it. This would allow us to maybe re-factor some of the control logic into a much simpler loop that takes into account the in-flight updates to the validator matrix. But since this is a big lift, I don't think it is worth doing this now.

**Comment by alsrdn** [comment]
bors try

File: node/src/types/node_config.rs [hunk 4]
```diff
@@ -33,6 +34,9 @@ pub struct NodeConfig {
 
     /// Flag which forces the node to resync all of the blocks.
     pub force_resync: bool,
+
+    /// Maximum time a node will wait for an upgrade to commit
```
Comment (rafal-ch) [inline node/src/types/node_config.rs]: Nit:

```suggestion
    /// Maximum time a node will wait for an upgrade to commit.
```

File: resources/local/config.toml [hunk 5]
```diff
@@ -21,6 +21,8 @@ control_logic_default_delay = '1sec'
 # Flag which forces the node to resync all of the blocks.
 force_resync = false
 
+# Maximum time a node will wait for an upgrade to commit
```
Comment (rafal-ch) [inline resources/local/config.toml]:
```suggestion
# Maximum time a node will wait for an upgrade to commit.
```

File: resources/production/config-example.toml [hunk 6]
```diff
@@ -21,6 +21,8 @@ control_logic_default_delay = '1sec'
 # Flag which forces the node to resync all of the blocks.
 force_resync = false
 
+# Maximum time a node will wait for an upgrade to commit
```
Comment (rafal-ch) [inline resources/production/config-example.toml]:
```suggestion
# Maximum time a node will wait for an upgrade to commit.
```

File: node/src/reactor/main_reactor.rs [hunk 7]
```diff
@@ -1391,38 +1391,13 @@ impl MainReactor {
...
         // the immediate switch block is stored and *also* marked complete.
         // This will allow the contract runtime to initialize properly (see
         // [`refresh_contract_runtime`]) when the reactor is transitioning from `CatchUp` to
         // `KeepUp`.
-        if state.is_marked_complete() {
-            debug!(
-                "MetaBlock: marked complete: {} {}",
-                block.height(),
-                block.hash(),
-            );
```
Comment (rafal-ch) [inline node/src/reactor/main_reactor.rs:1422]: This debug message is now gone. This is probably perfectly fine, because we'll have the `MetaBlock: update gossip state` logged, but just wanted to drag you attention to it for double check.

File: node/src/reactor/main_reactor/catch_up.rs [hunk 8]
```diff
@@ -120,26 +120,37 @@ impl MainReactor {
...
+                            self.control_logic_default_delay.into(),
+                        ))
+                    }
+                    Ok(None) => {
+                        // no trusted hash, no local block, might be genesis
+                        self.catch_up_check_genesis()
+                    }
+                    Err(storage_err) => {
+                        return Either::Right(CatchUpInstruction::Fatal(format!(
+                            "Could not read storage to find highest switch block header: {}",
```
Comment (rafal-ch) [inline node/src/reactor/main_reactor/catch_up.rs]: Nit, for the sake of consistency.

```suggestion
                            "CatchUp: could not read storage to find highest switch block header: {}",
```

File: node/src/types/sync_leap.rs (hunk 3 above)
Comment (rafal-ch) [reply node/src/types/sync_leap.rs:177]: Yeah, the fact that should-theoretically-be-simple `era_validator_weights()` got so clunky indicates that it might use some refactoring.

File: node/src/types/sync_leap.rs [hunk 9]
```diff
@@ -128,7 +128,18 @@ impl SyncLeap {
...
         fault_tolerance_fraction: Ratio<u64>,
+        protocol_config: &ProtocolConfig,
     ) -> impl Iterator<Item = EraValidatorWeights> + '_ {
+        // determine if the validator set has been updated in the
+        // current protocol version through an emergency upgrade
+        let validators_changed_in_current_protocol = protocol_config
+            .global_state_update
+            .as_ref()
+            .map_or(false, |global_state_update| {
+                global_state_update.validators.is_some()
```
Comment (rafal-ch) [inline node/src/types/sync_leap.rs:139]: Is it enough to just check for `validators.is_some()`? If there are validators in the file, but the same as current ones, they aren't actually "changed".

Comment (alsrdn) [reply node/src/types/sync_leap.rs:139]: Yes, the check is enough to determine that no change was made to the validator set whatsoever. 
To compare the validators set from the file we need the validator set from global state when the upgrade was made. This info requires a read to global state and we want to avoid that with this optimization; there is already a mechanism for doing this based on the results of `global_states_for_sync_across_upgrade` which would include the era that was filtered out here.

**Review by Fraser999 — APPROVED** [review]

File: node/src/reactor/main_reactor.rs (hunk 7 above)
Comment (alsrdn) [reply node/src/reactor/main_reactor.rs:1422]: Good point, I'll add it back since it helps with debugging.

File: node/src/reactor/main_reactor/catch_up.rs (hunk 8 above)
Comment (alsrdn) [reply node/src/reactor/main_reactor/catch_up.rs]: Fixed in https://github.com/casper-network/casper-node/pull/3971/commits/2b4c9ae04b1ad1c97b873fabb58367cc72e32144

File: node/src/reactor/main_reactor.rs (hunk 7 above)
Comment (alsrdn) [reply node/src/reactor/main_reactor.rs:1422]: Added in https://github.com/casper-network/casper-node/pull/3971/commits/2b4c9ae04b1ad1c97b873fabb58367cc72e32144

File: resources/production/config-example.toml (hunk 6 above)
Comment (alsrdn) [reply resources/production/config-example.toml]: Fixed in https://github.com/casper-network/casper-node/pull/3971/commits/2b4c9ae04b1ad1c97b873fabb58367cc72e32144

File: resources/local/config.toml (hunk 5 above)
Comment (alsrdn) [reply resources/local/config.toml]: Fixed in https://github.com/casper-network/casper-node/pull/3971/commits/2b4c9ae04b1ad1c97b873fabb58367cc72e32144

File: node/src/types/node_config.rs (hunk 4 above)
Comment (alsrdn) [reply node/src/types/node_config.rs]: Fixed in https://github.com/casper-network/casper-node/pull/3971/commits/2b4c9ae04b1ad1c97b873fabb58367cc72e32144

**Review by rafal-ch — APPROVED** [review]
LGTM :+1:
