### PR TITLE
Fix intermittent failure in SSE server test

### LINKED ISSUE #1560: Intermittent failure in SSE test
https://drone-auto-casper-network.casperlabs.io/casper-network/casper-node/515/3/3

### PR DESCRIPTION
**Pull request by Fraser999**
This makes the lagging client SSE server test more robust by changing it in a couple of ways:
* the test server now emits up to 100,000,000 events rather than the 100 previously
* the lagging clients now run slower by having a small sleep between reading each chunk of received data from the TCP stream
* the clients also pause for 5 seconds after connecting to the server but before starting to read data, to help ensure the server's TCP send buffer and client's TCP receive buffer are filled

Closes #1560.

### CODE REVIEW

File: node/src/components/event_stream_server/tests.rs [hunk 1]
```diff
@@ -111,6 +126,8 @@ impl ServerSyncBehavior {
     async fn sleep_if_required(&self) {
         if self.has_delay_between_events {
             time::sleep(DELAY_BETWEEN_EVENTS).await;
+        } else {
+            task::yield_now().await;
```
Comment (marc-casperlabs) [inline node/src/components/event_stream_server/tests.rs:130]: I'm not sure this is necessary, since we're calling an `async` function, thus giving the runtime a chance to intercept anyway? :)

**Review by marc-casperlabs — APPROVED** [review]
Looks good to me, although I can't judge right now if this fixes the behavior deterministically or we just ended up tweaking the numbers. The two barriers make me think the former though :)

**Review by darthsiroftardis — APPROVED** [review]
LGTM

File: node/src/components/event_stream_server/tests.rs (hunk 1 above)
Comment (Fraser999) [reply node/src/components/event_stream_server/tests.rs:130]: Yes, it shouldn't be strictly necessary.  However, the local tests seemed to benefit from this in the case of the lagging node.  My thinking is that this helps interleave the time slices more evenly between the client task and the server task.  We need the server task to actually progress (without a sleep) in order for the server to fill the buffers and kick the client off.  

However, it the server gets too big a time slice, it gets a chance to enqueue a _lot_ more events to the stream.  The only thing stopping the server doing that in its time slice is for the clients to detect the test has ended, allowing their futures to join and the call to stop the running server can happen.

So, it benefits us to give the clients control as frequently as possible.

**Comment by Fraser999** [comment]
> I can't judge right now if this fixes the behavior deterministically or we just ended up tweaking the numbers.

It's probably somewhere in between.  The clients are explicitly forced to run more slowly than the server now (which wasn't the case previously) which is more than just tweaking the numbers.  Given enough time, that should _always_ cause the clients to get kicked.

I didn't want to leave open the possibility of the test running for an unacceptably long time however, hence the additional (failure) stopping condition of allowing a maximum of 100,000,000 events in the test.  Local testing showed that in success cases, the event count didn't exceed 700,000.

Ultimately the test might still fail due to some unforeseen condition I haven't considered, but I think this change makes it much less likely.

**Comment by Fraser999** [comment]
bors merge

**Comment by Fraser999** [comment]
bors merge
