### PR TITLE
GH-3849: Get keys deserialize fix

### LINKED ISSUE #3849: get_keys should never deserialize a StoredValue
Keys iterator in global state should never deserialize a StoredValue. Currently, the iterator is supposed to yield keys matching a prefix, but it also deserializes a StoredValue just to throw it away.

### PR DESCRIPTION
**Pull request by mpapierski**
Closes #3849

This PR ensures that the `keys_with_prefix` iterator never deserializes `StoredValue`. This is accomplished by adding two zero-overhead types:
- `EnsureNeverDeserializes` wrapper for a `TrieStore` that will panic under debug mode when a value is deserialized, and
- `PanickingFromBytes` that wraps V, but the implementation will always panic when it's deserialized.

### CODE REVIEW

File: execution_engine/src/storage/trie_store/operations/debug_store.rs [hunk 1]
```diff
@@ -0,0 +1,54 @@
...
+
+use casper_hashing::Digest;
+use casper_types::bytesrepr::{self, FromBytes};
+
+use crate::storage::{store::Store, trie::Trie, trie_store::TrieStore};
+
+/// A [`TrieStore`] wrapper that panics in debug mode whenever an attempt to deserialize [`V`] is
+/// made, otherwise it behaves as a [`TrieStore`].
+///
+/// The debug panic is used to ensure that this wrapper has  To ensure this wrapper has zero
```
Comment (rafal-ch) [inline execution_engine/src/storage/trie_store/operations/debug_store.rs]: Some copy&paste error in the comment probably.

File: execution_engine/src/storage/trie_store/operations/tests/bytesrepr_utils.rs [hunk 2]
```diff
@@ -0,0 +1,37 @@
+use casper_types::bytesrepr::{self, FromBytes, ToBytes};
+
+#[derive(PartialEq, Eq, Debug, Clone)]
+pub(crate) struct PanickingFromBytes<T>(T);
```
Comment (rafal-ch) [inline execution_engine/src/storage/trie_store/operations/tests/bytesrepr_utils.rs:4]: Is this used anywhere else than tests?

File: execution_engine/src/storage/trie_store/operations/mod.rs [hunk 3]
```diff
@@ -1027,15 +1030,15 @@ enum KeysIteratorState<K, V, S: TrieStore<K, V>> {
...
+    trie: LazyTrieLeaf<K, V>,
     maybe_index: Option<usize>,
     path: Vec<u8>,
 }
 
 pub struct KeysIterator<'a, 'b, K, V, T, S: TrieStore<K, V>> {
     initial_descend: VecDeque<u8>,
     visited: Vec<VisitedTrieNode<K, V>>,
-    store: &'a S,
+    store: EnsureNeverDeserializes<'a, K, V, S>, //&'a S,
```
Comment (rafal-ch) [inline execution_engine/src/storage/trie_store/operations/mod.rs]: Stray comment? If no, please make it more descriptive.

File: execution_engine/src/storage/trie_store/operations/mod.rs [hunk 4]
```diff
@@ -1067,25 +1070,39 @@ where
...
+                                self.state = KeysIteratorState::Failed;
+                                return Some(Err(error.into()));
+                            }
+                        };
                         return Some(Ok(key));
                     }
                 }
-                Trie::Node { ref pointer_block } => {
+                LazyTrieLeaf::Right(Trie::Leaf { .. }) => {
+                    unreachable!("Lazy trie deserializer ensures that this variant never happens.")
```
Comment (rafal-ch) [inline execution_engine/src/storage/trie_store/operations/mod.rs:1103]: I'm wondering if we can encode this in the type system, so that this `unreachable!` arm is no longer needed.

File: execution_engine/src/storage/trie_store/operations/debug_store.rs [hunk 5]
```diff
@@ -0,0 +1,54 @@
...
+/// overhead, a debug assertion is used.
+pub(crate) struct EnsureNeverDeserializes<'a, K, V, S>(&'a S, PhantomData<*const (K, V)>)
```
Comment (alsrdn) [inline execution_engine/src/storage/trie_store/operations/debug_store.rs]: nit: since it's not a trait I'd rename this to something like `NonDeserializingStore`

File: execution_engine/src/storage/trie_store/operations/mod.rs [hunk 6]
```diff
@@ -1,11 +1,11 @@
+pub(crate) mod debug_store;
```
Comment (alsrdn) [inline execution_engine/src/storage/trie_store/operations/mod.rs]: nit: the name of the module is kind of weird since it's not only used for debug. I'd suggest naming it `store_wrappers` or similar.

File: execution_engine/src/storage/trie_store/operations/mod.rs [hunk 7]
```diff
@@ -1067,25 +1070,39 @@ where
...
-                        }
-                    };
-                    debug_assert!(key_bytes.starts_with(&path));
+                LazyTrieLeaf::Left(leaf_bytes) => {
+                    if leaf_bytes.is_empty() {
+                        self.state = KeysIteratorState::Failed;
+                        return Some(Err(bytesrepr::Error::Formatting.into()));
+                    }
+
+                    let key_bytes = &leaf_bytes[1..]; // Skip `Trie::Leaf` tag
```
Comment (alsrdn) [inline execution_engine/src/storage/trie_store/operations/mod.rs:1082]: nit: maybe it would be good to add a comment to `ToBytes`/`FromBytes` in `Trie` to point out that there are places where we do piecewise deserialization of it. It's good to know if we ever change that implementation that we also need to re-factor this code for it to work correctly.

**Review by alsrdn — APPROVED** [review]
A few nits but otherwise LGTM

File: execution_engine/src/storage/trie_store/operations/tests/bytesrepr_utils.rs (hunk 2 above)
Comment (mpapierski) [reply execution_engine/src/storage/trie_store/operations/tests/bytesrepr_utils.rs:4]: It's only used in tests, and in fact, it's in tests mod which is `#[cfg(test)]` only

File: execution_engine/src/storage/trie_store/operations/mod.rs (hunk 4 above)
Comment (mpapierski) [reply execution_engine/src/storage/trie_store/operations/mod.rs:1103]: We could, something like `enum LazyTrie<K, V> { Leaf(Bytes, PhantomData<(K, V)>), Node(TrieNode), Extension(TrieExtension) }` etc. Now that we'll do more lazy trie leaf deserialization I added a ticket to deal with this

File: execution_engine/src/storage/trie_store/operations/mod.rs (hunk 7 above)
Comment (mpapierski) [reply execution_engine/src/storage/trie_store/operations/mod.rs:1082]: Added comment

File: execution_engine/src/storage/trie_store/operations/mod.rs (hunk 6 above)
Comment (mpapierski) [reply execution_engine/src/storage/trie_store/operations/mod.rs]: Renamed

File: execution_engine/src/storage/trie_store/operations/debug_store.rs (hunk 5 above)
Comment (mpapierski) [reply execution_engine/src/storage/trie_store/operations/debug_store.rs]: Renamed

File: execution_engine/src/storage/trie_store/operations/mod.rs (hunk 3 above)
Comment (mpapierski) [reply execution_engine/src/storage/trie_store/operations/mod.rs]: Removed

File: execution_engine/src/storage/trie_store/operations/debug_store.rs (hunk 1 above)
Comment (mpapierski) [reply execution_engine/src/storage/trie_store/operations/debug_store.rs]: Fixed

File: execution_engine/src/storage/trie_store/operations/mod.rs (hunk 4 above)
Comment (mpapierski) [reply execution_engine/src/storage/trie_store/operations/mod.rs:1103]: Ticket https://github.com/casper-network/casper-node/issues/3994

**Review by rafal-ch — APPROVED** [review]
LGTM :+1:
