### PR TITLE
node/max_ttl: remove error for timestamp chronology

### LINKED ISSUE #4160: Investigate failed sync test
The nctl sync_test.sh failed in this nightly run: https://drone-auto-casper-network.casperlabs.io/casper-network/casper-node/8714/1/4

### PR DESCRIPTION
**Pull request by alsrdn**
It is possible that if a node just caught up, its highest orphaned block is within the current active era.
Right now the node errors because the `latest_switch_block_timestamp` is lower than the `highest_orphaned_block_timestamp` but this is not necessary.

Fixes: https://github.com/casper-network/casper-node/issues/4160

### CODE REVIEW

**Review by EdHastingsCasperAssociation — APPROVED** [review]

File: node/src/types/max_ttl.rs [hunk 1]
```diff
@@ -18,22 +18,18 @@ impl MaxTtl {
     }
 
     /// Determine if two timestamps are more than max_ttl apart.
-    pub fn ttl_elapsed(&self, higher: Timestamp, lower: Timestamp) -> Result<bool, String> {
-        if lower > higher {
-            Err("invalid timestamp chronology".to_string())
-        } else {
-            Ok(lower < higher.saturating_sub(self.0))
-        }
+    pub fn ttl_elapsed(&self, higher: Timestamp, lower: Timestamp) -> bool {
```
Comment (EdHastingsCasperAssociation) [inline node/src/types/max_ttl.rs]: /// If rearview is earlier than (vantage - ttl duration), ttl has elapsed.
    pub fn ttl_elapsed(&self, vantage: Timestamp, rearview: Timestamp) -> bool {
        rearview < vantage.saturating_sub(self.0)
    }

Comment (alsrdn) [reply node/src/types/max_ttl.rs]: renamed in https://github.com/casper-network/casper-node/pull/4195/commits/ef1b648f1dc0bd9450c9938d77939a6a2a310970
