### PR TITLE
Make Highway timers configurable; request state periodically from a random peer.

### LINKED ISSUE #1914: Don't Request All The Latest States From All Of The Peers At Once
Currently a node waits for the whole `standstill_alert` and then requests the latest state from _all_ peers. That means it will fail to make progress for a long time and then send way too many messages (small ones, fortunately).

We should instead have a shorter timeout for this and periodically request the latest state from just one peer. Maybe even unconditionally, just to add another source.

### PR DESCRIPTION
**Pull request by afck**
This separates the standstill alert — restart if no progress is made — from requesting the latest protocol state, and makes those timers configurable separately. The latest protocol state is requested from only one peer instead of from everyone.

Closes #1914.

### CODE REVIEW

File: node/src/components/consensus/protocols/highway/tests.rs [hunk 1]
```diff
@@ -95,13 +94,14 @@ where
         0,
         start_timestamp,
     );
-    // We expect for messages:
```
Comment (goral09) [inline node/src/components/consensus/protocols/highway/tests.rs:98]: 😅

File: utils/nctl/sh/scenarios/configs/gov96.config.toml [hunk 2]
```diff
@@ -47,16 +47,18 @@ unit_hashes_folder = "../node-storage"
 # The duration for which incoming vertices with missing dependencies should be kept in a queue.
 pending_vertex_timeout = '1min'
 
-# If the current era's protocol state has not progressed for this long, request the latest state
-# from peers.
-standstill_timeout = '30sec'
+# If the current era's protocol state has not progressed for this long, shut down.
+# standstill_timeout = '30min'
```
Comment (goral09) [inline utils/nctl/sh/scenarios/configs/gov96.config.toml]: Why are commenting it out? That could in theory affect the test outcome.

File: node/src/components/consensus/protocols/highway.rs [hunk 3]
```diff
@@ -471,76 +472,56 @@ impl<I: NodeIdT, C: Context + 'static> HighwayProtocol<I, C> {
...
-            self.standstill_timeout,
+            "requesting latest state from random peer",
         );
-        // Record the current panorama and schedule the next standstill check.
-        self.last_panorama = self.highway.state().panorama().clone();
-        vec![ProtocolOutcome::ScheduleTimer(
-            now + self.standstill_timeout,
-            TIMER_ID_STANDSTILL_ALERT,
-        )]
+        // We haven't made any progress. Request latest panorama from peers and schedule
```
Comment (goral09) [inline node/src/components/consensus/protocols/highway.rs]: Aren't we requesting the latest state regardless of whether we made any progress or not?

**Review by goral09 — APPROVED** [review]
Looks good. I'm wondering whether we should base the state request timer on the round length. Making a request every 5/10/20s could be too much if rounds can be at fastest 60s etc. Although, that doesn't work the other way around (I think): if rounds are really short then we shouldn't need to make the request that often since we should keep receiving units more often (shorter rounds).

OK, I think I've convinced myself that we don't have to base that timer on the round length.

File: utils/nctl/sh/scenarios/configs/gov96.config.toml (hunk 2 above)
Comment (afck) [reply utils/nctl/sh/scenarios/configs/gov96.config.toml]: Good point: I guess it's best to keep it enabled and set to something shorter (3 minutes?) in the tests, so they don't just keep running if they go wrong.

Comment (goral09) [reply utils/nctl/sh/scenarios/configs/gov96.config.toml]: A good start would be to simply leave it as it was before - but we have to remember that it actually was twice that much b/c it used that timer twice before shutting down.

**Comment by afck** [comment]
@goral09: Thanks, I addressed your two comments. I'm not sure it's a good idea to apply some formula to determine the request frequency: Giving the interval explicitly in the config is easier to understand. And the overhead should be minimal anyway: The request consists of one panorama, so it's about the size of a unit, and we send it to one peer at a time. In comparison, we send two units to _every_ peer in every round.

**Comment by goral09** [comment]
I agree @afck 👍

File: utils/nctl/sh/scenarios/configs/gov96.config.toml (hunk 2 above)
Comment (afck) [reply utils/nctl/sh/scenarios/configs/gov96.config.toml]: You're right, there's no reason to change that behavior in this PR; I reset them.

**Review by fizyk20 — APPROVED** [review]

**Comment by fizyk20** [comment]
bors merge
